# Pandas Essential Training

The following cell has the year for the olympics

In [5]:
year = 1986
year + 8

1994

## Using pandas

In [6]:
!pip install pandas==2.0.2

Collecting pandas==2.0.2
  Downloading pandas-2.0.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas==2.0.2) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas==2.0.2) (2025.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.11/dist-packages (from pandas==2.0.2) (2025.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.11/dist-packages (from pandas==2.0.2) (1.26.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas==2.0.2) (1.17.0)
Downloading pandas-2.0.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 61.3 MB/s eta 0:00:00
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.0.2 which is incompatible.
plotnine 0.14.5 requires pandas>=2.2.0, but you have pandas 2.0.2 which is incompatible.
mizani 0.13.1 requires pandas>=2.2.0, but you have pandas 2.0.2 which is incompatible.
xarray 2025.1.2 requires pandas>=2.1, but you have pandas 2.0.2 which is incompatible.
Successfully installed pandas-2.0.2

In [2]:
import pandas

In [3]:
import pandas as pd

In [4]:
pd.__version__

'2.2.2'

In [5]:
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annotations',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'describe_option',
 'errors',
 'eval',
 'factorize',
 'from_dummies',
 'get_dummies',
 'get_option',
 'infer_freq',
 'interval_range',
 'io',
 'isna',
 'isnull',
 'json_normalize',
 'lreshape',
 'melt',
 'merge',
 'merge_asof',
 'merge_ordered',
 'notna',
 'notnull',
 'offsets',
 'option_context',
 'options',
 'pandas',
 'period_range',
 'pivot',
 'pivot_table',
 'plotting',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_gbq',
 'read_hdf',
 'read_html',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'read_xml',
 'reset_option',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'test',
 'testing',
 'timedelta_range',
 'to_datetime',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tseries',
 'unique',
 'util',
 'value_counts',
 'wide_to_long']

In [6]:
help(pd.read_csv)

Help on function read_csv in module pandas.io.parsers.readers:

read_csv(filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]', *, sep: 'str | None | lib.NoDefault' = <no_default>, delimiter: 'str | None | lib.NoDefault' = None, header: "int | Sequence[int] | None | Literal['infer']" = 'infer', names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>, index_col: 'IndexLabel | Literal[False] | None' = None, usecols: 'UsecolsArgType' = None, dtype: 'DtypeArg | None' = None, engine: 'CSVEngine | None' = None, converters: 'Mapping[Hashable, Callable] | None' = None, true_values: 'list | None' = None, false_values: 'list | None' = None, skipinitialspace: 'bool' = False, skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None, skipfooter: 'int' = 0, nrows: 'int | None' = None, na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None, keep_default_na: 'bool' = True, na_filter: 'bool' = True, verbose: 'bool | lib.NoDefault' = <no_default>, skip_blank_lines: 'bool' = True, parse_dates: 'bool | Sequence[Hashable] | None' = None, infer_datetime_format: 'bool | lib.NoDefault' = <no_default>, keep_date_col: 'bool | lib.NoDefault' = <no_default>, date_parser: 'Callable | lib.NoDefault' = <no_default>, date_format: 'str | dict[Hashable, str] | None' = None, dayfirst: 'bool' = False, cache_dates: 'bool' = True, iterator: 'bool' = False, chunksize: 'int | None' = None, compression: 'CompressionOptions' = 'infer', thousands: 'str | None' = None, decimal: 'str' = '.', lineterminator: 'str | None' = None, quotechar: 'str' = '"', quoting: 'int' = 0, doublequote: 'bool' = True, escapechar: 'str | None' = None, comment: 'str | None' = None, encoding: 'str | None' = None, encoding_errors: 'str | None' = 'strict', dialect: 'str | csv.Dialect | None' = None, on_bad_lines: 'str' = 'error', delim_whitespace: 'bool | lib.NoDefault' = <no_default>, low_memory: 'bool' = True, memory_map: 'bool' = False, float_precision: "Literal['high', 'legacy'] | None" = None, storage_options: 'StorageOptions | None' = None, dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>) -> 'DataFrame | TextFileReader'
    Read a comma-separated values (csv) file into DataFrame.

    Also supports optionally iterating or breaking of the file
    into chunks.

    Additional help can be found in the online docs for
    `IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

    Parameters
    ----------
    filepath_or_buffer : str, path object or file-like object
        Any valid string path is acceptable. The string could be a URL. Valid
        URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
        expected. A local file could be: file://localhost/path/to/table.csv.

        If you want to pass in a path object, pandas accepts any ``os.PathLike``.

        By file-like object, we refer to objects with a ``read()`` method, such as
        a file handle (e.g. via builtin ``open`` function) or ``StringIO``.
    sep : str, default ','
        Character or regex pattern to treat as the delimiter. If ``sep=None``, the
        C engine cannot automatically detect
        the separator, but the Python parsing engine can, meaning the latter will
        be used and automatically detect the separator from only the first valid
        row of the file by Python's builtin sniffer tool, ``csv.Sniffer``.
        In addition, separators longer than 1 character and different from
        ``'\s+'`` will be interpreted as regular expressions and will also force
        the use of the Python parsing engine. Note that regex delimiters are prone
        to ignoring quoted data. Regex example: ``'\r\t'``.
    delimiter : str, optional
        Alias for ``sep``.
    header : int, Sequence of int, 'infer' or None, default 'infer'
        Row number(s) containing column labels and marking the start of the
        data (zero-indexed). Default behavior is to infer the column names: if no ``names``
        are passed the behavior is identical to ``header=0`` and column
        names are inferred from the first line of the file, if column
        names are passed explicitly to ``names`` then the behavior is identical to
        ``header=None``. Explicitly pass ``header=0`` to be able to
        replace existing names. The header can be a list of integers that
        specify row locations for a :class:`~pandas.MultiIndex` on the columns
        e.g. ``[0, 1, 3]``. Intervening rows that are not specified will be
        skipped (e.g. 2 in this example is skipped). Note that this
        parameter ignores commented lines and empty lines if
        ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
        data rather than the first line of the file.
    names : Sequence of Hashable, optional
        Sequence of column labels to apply. If the file contains a header row,
        then you should explicitly pass ``header=0`` to override the column names.
        Duplicates in this list are not allowed.
    index_col : Hashable, Sequence of Hashable or False, optional
      Column(s) to use as row label(s), denoted either by column labels or column
      indices.  If a sequence of labels or indices is given, :class:`~pandas.MultiIndex`
      will be formed for the row labels.

      Note: ``index_col=False`` can be used to force pandas to *not* use the first
      column as the index, e.g., when you have a malformed file with delimiters at
      the end of each line.
    usecols : Sequence of Hashable or Callable, optional
        Subset of columns to select, denoted either by column labels or column indices.
        If list-like, all elements must either
        be positional (i.e. integer indices into the document columns) or strings
        that correspond to column names provided either by the user in ``names`` or
        inferred from the document header row(s). If ``names`` are given, the document
        header row(s) are not taken into account. For example, a valid list-like
        ``usecols`` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
        Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
        To instantiate a :class:`~pandas.DataFrame` from ``data`` with element order
        preserved use ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]``
        for columns in ``['foo', 'bar']`` order or
        ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
        for ``['bar', 'foo']`` order.

        If callable, the callable function will be evaluated against the column
        names, returning names where the callable function evaluates to ``True``. An
        example of a valid callable argument would be ``lambda x: x.upper() in
        ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
        parsing time and lower memory usage.
    dtype : dtype or dict of {Hashable : dtype}, optional
        Data type(s) to apply to either the whole dataset or individual columns.
        E.g., ``{'a': np.float64, 'b': np.int32, 'c': 'Int64'}``
        Use ``str`` or ``object`` together with suitable ``na_values`` settings
        to preserve and not interpret ``dtype``.
        If ``converters`` are specified, they will be applied INSTEAD
        of ``dtype`` conversion.

        .. versionadded:: 1.5.0

            Support for ``defaultdict`` was added. Specify a ``defaultdict`` as input where
            the default determines the ``dtype`` of the columns which are not explicitly
            listed.
    engine : {'c', 'python', 'pyarrow'}, optional
        Parser engine to use. The C and pyarrow engines are faster, while the python engine
        is currently more feature-complete. Multithreading is currently only supported by
        the pyarrow engine.

        .. versionadded:: 1.4.0

            The 'pyarrow' engine was added as an *experimental* engine, and some features
            are unsupported, or may not work correctly, with this engine.
    converters : dict of {Hashable : Callable}, optional
        Functions for converting values in specified columns. Keys can either
        be column labels or column indices.
    true_values : list, optional
        Values to consider as ``True`` in addition to case-insensitive variants of 'True'.
    false_values : list, optional
        Values to consider as ``False`` in addition to case-insensitive variants of 'False'.
    skipinitialspace : bool, default False
        Skip spaces after delimiter.
    skiprows : int, list of int or Callable, optional
        Line numbers to skip (0-indexed) or number of lines to skip (``int``)
        at the start of the file.

        If callable, the callable function will be evaluated against the row
        indices, returning ``True`` if the row should be skipped and ``False`` otherwise.
        An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
    skipfooter : int, default 0
        Number of lines at bottom of file to skip (Unsupported with ``engine='c'``).
    nrows : int, optional
        Number of rows of file to read. Useful for reading pieces of large files.
    na_values : Hashable, Iterable of Hashable or dict of {Hashable : Iterable}, optional
        Additional strings to recognize as ``NA``/``NaN``. If ``dict`` passed, specific
        per-column ``NA`` values.  By default the following values are interpreted as
        ``NaN``: " ", "#N/A", "#N/A N/A", "#NA", "-1.#IND", "-1.#QNAN", "-NaN", "-nan",
        "1.#IND", "1.#QNAN", "<NA>", "N/A", "NA", "NULL", "NaN", "None",
        "n/a", "nan", "null ".

    keep_default_na : bool, default True
        Whether or not to include the default ``NaN`` values when parsing the data.
        Depending on whether ``na_values`` is passed in, the behavior is as follows:

        * If ``keep_default_na`` is ``True``, and ``na_values`` are specified, ``na_values``
          is appended to the default ``NaN`` values used for parsing.
        * If ``keep_default_na`` is ``True``, and ``na_values`` are not specified, only
          the default ``NaN`` values are used for parsing.
        * If ``keep_default_na`` is ``False``, and ``na_values`` are specified, only
          the ``NaN`` values specified ``na_values`` are used for parsing.
        * If ``keep_default_na`` is ``False``, and ``na_values`` are not specified, no
          strings will be parsed as ``NaN``.

        Note that if ``na_filter`` is passed in as ``False``, the ``keep_default_na`` and
        ``na_values`` parameters will be ignored.
    na_filter : bool, default True
        Detect missing value markers (empty strings and the value of ``na_values``). In
        data without any ``NA`` values, passing ``na_filter=False`` can improve the
        performance of reading a large file.
    verbose : bool, default False
        Indicate number of ``NA`` values placed in non-numeric columns.

        .. deprecated:: 2.2.0
    skip_blank_lines : bool, default True
        If ``True``, skip over blank lines rather than interpreting as ``NaN`` values.
    parse_dates : bool, list of Hashable, list of lists or dict of {Hashable : list}, default False
        The behavior is as follows:

        * ``bool``. If ``True`` -> try parsing the index. Note: Automatically set to
          ``True`` if ``date_format`` or ``date_parser`` arguments have been passed.
        * ``list`` of ``int`` or names. e.g. If ``[1, 2, 3]`` -> try parsing columns 1, 2, 3
          each as a separate date column.
        * ``list`` of ``list``. e.g.  If ``[[1, 3]]`` -> combine columns 1 and 3 and parse
          as a single date column. Values are joined with a space before parsing.
        * ``dict``, e.g. ``{'foo' : [1, 3]}`` -> parse columns 1, 3 as date and call
          result 'foo'. Values are joined with a space before parsing.

        If a column or index cannot be represented as an array of ``datetime``,
        say because of an unparsable value or a mixture of timezones, the column
        or index will be returned unaltered as an ``object`` data type. For
        non-standard ``datetime`` parsing, use :func:`~pandas.to_datetime` after
        :func:`~pandas.read_csv`.

        Note: A fast-path exists for iso8601-formatted dates.
    infer_datetime_format : bool, default False
        If ``True`` and ``parse_dates`` is enabled, pandas will attempt to infer the
        format of the ``datetime`` strings in the columns, and if it can be inferred,
        switch to a faster method of parsing them. In some cases this can increase
        the parsing speed by 5-10x.

        .. deprecated:: 2.0.0
            A strict version of this argument is now the default, passing it has no effect.

    keep_date_col : bool, default False
        If ``True`` and ``parse_dates`` specifies combining multiple columns then
        keep the original columns.
    date_parser : Callable, optional
        Function to use for converting a sequence of string columns to an array of
        ``datetime`` instances. The default uses ``dateutil.parser.parser`` to do the
        conversion. pandas will try to call ``date_parser`` in three different ways,
        advancing to the next if an exception occurs: 1) Pass one or more arrays
        (as defined by ``parse_dates``) as arguments; 2) concatenate (row-wise) the
        string values from the columns defined by ``parse_dates`` into a single array
        and pass that; and 3) call ``date_parser`` once for each row using one or
        more strings (corresponding to the columns defined by ``parse_dates``) as
        arguments.

        .. deprecated:: 2.0.0
           Use ``date_format`` instead, or read in as ``object`` and then apply
           :func:`~pandas.to_datetime` as-needed.
    date_format : str or dict of column -> format, optional
        Format to use for parsing dates when used in conjunction with ``parse_dates``.
        The strftime to parse time, e.g. :const:`"%d/%m/%Y"`. See
        `strftime documentation
        <https://docs.python.org/3/library/datetime.html
        #strftime-and-strptime-behavior>`_ for more information on choices, though
        note that :const:`"%f"` will parse all the way up to nanoseconds.
        You can also pass:

        - "ISO8601", to parse any `ISO8601 <https://en.wikipedia.org/wiki/ISO_8601>`_
            time string (not necessarily in exactly the same format);
        - "mixed", to infer the format for each element individually. This is risky,
            and you should probably use it along with `dayfirst`.

        .. versionadded:: 2.0.0
    dayfirst : bool, default False
        DD/MM format dates, international and European format.
    cache_dates : bool, default True
        If ``True``, use a cache of unique, converted dates to apply the ``datetime``
        conversion. May produce significant speed-up when parsing duplicate
        date strings, especially ones with timezone offsets.

    iterator : bool, default False
        Return ``TextFileReader`` object for iteration or getting chunks with
        ``get_chunk()``.
    chunksize : int, optional
        Number of lines to read from the file per chunk. Passing a value will cause the
        function to return a ``TextFileReader`` object for iteration.
        See the `IO Tools docs
        <https://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
        for more information on ``iterator`` and ``chunksize``.

    compression : str or dict, default 'infer'
        For on-the-fly decompression of on-disk data. If 'infer' and 'filepath_or_buffer' is
        path-like, then detect compression from the following extensions: '.gz',
        '.bz2', '.zip', '.xz', '.zst', '.tar', '.tar.gz', '.tar.xz' or '.tar.bz2'
        (otherwise no compression).
        If using 'zip' or 'tar', the ZIP file must contain only one data file to be read in.
        Set to ``None`` for no decompression.
        Can also be a dict with key ``'method'`` set
        to one of {``'zip'``, ``'gzip'``, ``'bz2'``, ``'zstd'``, ``'xz'``, ``'tar'``} and
        other key-value pairs are forwarded to
        ``zipfile.ZipFile``, ``gzip.GzipFile``,
        ``bz2.BZ2File``, ``zstandard.ZstdDecompressor``, ``lzma.LZMAFile`` or
        ``tarfile.TarFile``, respectively.
        As an example, the following could be passed for Zstandard decompression using a
        custom compression dictionary:
        ``compression={'method': 'zstd', 'dict_data': my_compression_dict}``.

        .. versionadded:: 1.5.0
            Added support for `.tar` files.

        .. versionchanged:: 1.4.0 Zstandard support.

    thousands : str (length 1), optional
        Character acting as the thousands separator in numerical values.
    decimal : str (length 1), default '.'
        Character to recognize as decimal point (e.g., use ',' for European data).
    lineterminator : str (length 1), optional
        Character used to denote a line break. Only valid with C parser.
    quotechar : str (length 1), optional
        Character used to denote the start and end of a quoted item. Quoted
        items can include the ``delimiter`` and it will be ignored.
    quoting : {0 or csv.QUOTE_MINIMAL, 1 or csv.QUOTE_ALL, 2 or csv.QUOTE_NONNUMERIC, 3 or csv.QUOTE_NONE}, default csv.QUOTE_MINIMAL
        Control field quoting behavior per ``csv.QUOTE_*`` constants. Default is
        ``csv.QUOTE_MINIMAL`` (i.e., 0) which implies that only fields containing special
        characters are quoted (e.g., characters defined in ``quotechar``, ``delimiter``,
        or ``lineterminator``.
    doublequote : bool, default True
       When ``quotechar`` is specified and ``quoting`` is not ``QUOTE_NONE``, indicate
       whether or not to interpret two consecutive ``quotechar`` elements INSIDE a
       field as a single ``quotechar`` element.
    escapechar : str (length 1), optional
        Character used to escape other characters.
    comment : str (length 1), optional
        Character indicating that the remainder of line should not be parsed.
        If found at the beginning
        of a line, the line will be ignored altogether. This parameter must be a
        single character. Like empty lines (as long as ``skip_blank_lines=True``),
        fully commented lines are ignored by the parameter ``header`` but not by
        ``skiprows``. For example, if ``comment='#'``, parsing
        ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in ``'a,b,c'`` being
        treated as the header.
    encoding : str, optional, default 'utf-8'
        Encoding to use for UTF when reading/writing (ex. ``'utf-8'``). `List of Python
        standard encodings
        <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .

    encoding_errors : str, optional, default 'strict'
        How encoding errors are treated. `List of possible values
        <https://docs.python.org/3/library/codecs.html#error-handlers>`_ .

        .. versionadded:: 1.3.0

    dialect : str or csv.Dialect, optional
        If provided, this parameter will override values (default or not) for the
        following parameters: ``delimiter``, ``doublequote``, ``escapechar``,
        ``skipinitialspace``, ``quotechar``, and ``quoting``. If it is necessary to
        override values, a ``ParserWarning`` will be issued. See ``csv.Dialect``
        documentation for more details.
    on_bad_lines : {'error', 'warn', 'skip'} or Callable, default 'error'
        Specifies what to do upon encountering a bad line (a line with too many fields).
        Allowed values are :

        - ``'error'``, raise an Exception when a bad line is encountered.
        - ``'warn'``, raise a warning when a bad line is encountered and skip that line.
        - ``'skip'``, skip bad lines without raising or warning when they are encountered.

        .. versionadded:: 1.3.0

        .. versionadded:: 1.4.0


In [7]:
pd.read_csv?

Pandas documentation: https://pandas.pydata.org/docs/reference/index.html

## Reading tabular data into pandas

In [8]:
!wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

--2025-02-12 02:14:31--  https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/jonfernandes/pandas_essential/main/olympics_1896_2004.csv [following]
--2025-02-12 02:14:31--  https://raw.githubusercontent.com/jonfernandes/pandas_essential/main/olympics_1896_2004.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2398388 (2.3M) [text/plain]
Saving to: ‘olympics_1896_2004.csv’

olympics_1896_2004. 100%[===================>]   2.29M  --.-KB/s    in 0.01s

2025-02-12 02:14:31 (164 MB/s) - ‘olympics_1896_2004.csv’ saved [2398388/2398388]

In [10]:
from google.colab import files
files.upload()

{}

In [11]:
!ls -la

total 2360
drwxr-xr-x 1 root root    4096 Feb 12 02:14 .
drwxr-xr-x 1 root root    4096 Feb 12 02:10 ..
drwxr-xr-x 4 root root    4096 Feb 10 14:24 .config
-rw-r--r-- 1 root root 2398388 Feb 12 02:14 olympics_1896_2004.csv
drwxr-xr-x 1 root root    4096 Feb 10 14:25 sample_data

In [12]:
pd.read_csv?

In [13]:
pd.read_csv('olympics_1896_2004.csv')

,"This is a list of medallists at the Summer Olympic Games (1896-2004) with details of the year of the olympics, city, sport, discipline, athlete name, gender, event and medal",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"DISCLAIMER: No guarantees, express or implied,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
...,...,...,...,...,...,...,...,...,...,...,...
27174,2004,Athens,Fencing,Fencing,"LOGOUNOVA, Tatiana",RUS,Women,épée team,W,Gold,1
27175,2004,Athens,Fencing,Fencing,"SIVKOVA, Anna",RUS,Women,épée team,W,Gold,1
27176,2004,Athens,Fencing,Fencing,"BOKEL, Claudia",GER,Women,épée team,W,Silver,2
27177,2004,Athens,Fencing,Fencing,"DUPLITZER, Imke",GER,Women,épée team,W,Silver,2
27178,2004,Athens,Fencing,Fencing,"HEIDEMANN, Britta",GER,Women,épée team,W,Silver,2

In [14]:
pd.read_csv(filepath_or_buffer='olympics_1896_2004.csv')

,"This is a list of medallists at the Summer Olympic Games (1896-2004) with details of the year of the olympics, city, sport, discipline, athlete name, gender, event and medal",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"DISCLAIMER: No guarantees, express or implied,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
...,...,...,...,...,...,...,...,...,...,...,...
27174,2004,Athens,Fencing,Fencing,"LOGOUNOVA, Tatiana",RUS,Women,épée team,W,Gold,1
27175,2004,Athens,Fencing,Fencing,"SIVKOVA, Anna",RUS,Women,épée team,W,Gold,1
27176,2004,Athens,Fencing,Fencing,"BOKEL, Claudia",GER,Women,épée team,W,Silver,2
27177,2004,Athens,Fencing,Fencing,"DUPLITZER, Imke",GER,Women,épée team,W,Silver,2
27178,2004,Athens,Fencing,Fencing,"HEIDEMANN, Britta",GER,Women,épée team,W,Silver,2

In [16]:
df = pd.read_csv('olympics_1896_2004.csv')
df

,"This is a list of medallists at the Summer Olympic Games (1896-2004) with details of the year of the olympics, city, sport, discipline, athlete name, gender, event and medal",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"DISCLAIMER: No guarantees, express or implied,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
...,...,...,...,...,...,...,...,...,...,...,...
27174,2004,Athens,Fencing,Fencing,"LOGOUNOVA, Tatiana",RUS,Women,épée team,W,Gold,1
27175,2004,Athens,Fencing,Fencing,"SIVKOVA, Anna",RUS,Women,épée team,W,Gold,1
27176,2004,Athens,Fencing,Fencing,"BOKEL, Claudia",GER,Women,épée team,W,Silver,2
27177,2004,Athens,Fencing,Fencing,"DUPLITZER, Imke",GER,Women,épée team,W,Silver,2
27178,2004,Athens,Fencing,Fencing,"HEIDEMANN, Britta",GER,Women,épée team,W,Silver,2

In [17]:
df = pd.read_csv('olympics_1896_2004.csv', skiprows=5)
df

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold,1
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver,2
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze,3
3,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze,3
4,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold,1
...,...,...,...,...,...,...,...,...,...,...,...
27169,2004,Athens,Fencing,Fencing,"LOGOUNOVA, Tatiana",RUS,Women,épée team,W,Gold,1
27170,2004,Athens,Fencing,Fencing,"SIVKOVA, Anna",RUS,Women,épée team,W,Gold,1
27171,2004,Athens,Fencing,Fencing,"BOKEL, Claudia",GER,Women,épée team,W,Silver,2
27172,2004,Athens,Fencing,Fencing,"DUPLITZER, Imke",GER,Women,épée team,W,Silver,2
27173,2004,Athens,Fencing,Fencing,"HEIDEMANN, Britta",GER,Women,épée team,W,Silver,2

In [18]:
filename = "olympics_1896_2004.csv"

In [20]:
from google.colab import files
files.upload()

Saving metro_manila_schools.csv to metro_manila_schools.csv

{'metro_manila_schools.csv': b'name,city,latitude,longitude,geometry\r\nGideon Academy,Gideon Academy,1636323.386,13469099.12,POINT (120.99497599999998 14.540697599999998)\r\n,Unknown,1648428.754,13482556.1,POINT (121.1158621 14.645933699999995)\r\nThe Children\'s House School,The Children\'s House School,1648888.725,13482812.06,POINT (121.11816149999997 14.6499314)\r\nVictoria School,Victoria School,1649058.624,13482285.76,POINT (121.1134336 14.651408)\r\nMy Playland Learning Center,My Playland Learning Center,1649870.979,13482410.32,POINT (121.1145526 14.658468099999997)\r\nMinds in Motion Learning Center,Minds in Motion Learning Center,1648506.798,13482475.72,POINT (121.11514010000002 14.646612)\r\nCovenant Children Academy,Marikina,1648379.693,13482882.36,POINT (121.11879300000001 14.645507299999997)\r\nDC Integrated School for Early Achievers,DC Integrated School for Early Achievers,1649864.765,13482391.6,POINT (121.11438439999998 14.6584141)\r\nBright Star Learning Center,Bright Star Learning Center,1645682.374,13480423.36,POINT (121.09670340000001 14.622062899999998)\r\nSta. Clara Academy,Marikina,1645654.671,13480167.3,POINT (121.09440319999997 14.621822099999997)\r\nTechnological Institute of the Philippines,Manila,1643200.606,13468178,POINT (120.98670150000001 14.600489799999997)\r\nAsian School Of Christian,Quezon City,1646394.355,13469339.21,POINT (120.9971328 14.628251500000001)\r\nSt. Joseph Christian School,Caloocan,1659727.958,13473694.64,POINT (121.03625830000001 14.744115999999998)\r\nLeonor Rivera School,Manila,1644891.69,13466504.93,POINT (120.971672 14.615190000000002)\r\nDivine Grace School,Caloocan,1659314.142,13476486.72,POINT (121.06134 14.740520999999998)\r\n"Capitol Hills Christian School, Inc.",Quezon City,1653484.131,13480694.19,POINT (121.09913630000001 14.6898669)\r\nDivine Mercy College,Caloocan,1650183.025,13467376.86,POINT (120.97950470000002 14.661179999999998)\r\nLiving Stones Christian Academy,Mandaluyong,1641099.971,13475086.28,POINT (121.0487596 14.582228099999996)\r\nMother Gonly Memorial Institute,Quezon City,1647979.663,13472051.96,POINT (121.02150179999997 14.6420305)\r\nSt. Jerome Learning Center (sunrise Learning Schoo,Quezon City,1644838.08,13476741.51,POINT (121.0636288 14.614723999999997)\r\nChildren\'s House Of Learning And Development,Quezon City,1655084.167,13477622.18,POINT (121.07153999999998 14.70377)\r\nSt. John Institute of Technology,Valenzuela,1653460.436,13472703.09,POINT (121.02735099999997 14.689660999999997)\r\nSouthern Rizal Institute,Pateros,1636198.309,13477296.13,POINT (121.068611 14.539610000000003)\r\nSt. Gabriel Academy,Malabon,1649900.689,13467558.04,POINT (120.9811323 14.658726299999998)\r\nJuan Luna High School,Manila,1643777.072,13468562.78,POINT (120.990158 14.605501)\r\nPara\xc3\xb1aque Community High School,Para\xc3\xb1aque,1634557.391,13469299.94,POINT (120.99678 14.525341)\r\nVicente Romualdez Integrated School,Manila,1643435.415,13470682.64,POINT (121.009201 14.602530999999999)\r\nLa Immaculada Concepcion School,Pasig,1638532.968,13478499.6,POINT (121.07942199999998 14.55991)\r\nBagong Lote Elementary School,Malabon,1651145.663,13469439.98,POINT (120.99803800000001 14.6695458)\r\nIETI School,IETI School,1646157.781,13475055.89,POINT (121.0484866 14.626195200000002)\r\nCamilio Osias School,Manila,1646333.207,13466810.61,POINT (120.974418 14.627720000000002)\r\nPhilippine Sun Yat Sen High School,Manila,1643358.342,13467311.77,POINT (120.97892000000002 14.601860999999998)\r\nLycee D Saint C. Y. R.,Para\xc3\xb1aque,1627790.713,13471019.71,POINT (121.01222900000002 14.466490000000002)\r\nLifespring Christian School,Quezon City,1646527.789,13470680.45,POINT (121.00918140000002 14.6294113)\r\nDiliman Christian Academy,Quezon City,1650824.423,13476303.4,POINT (121.0596932 14.666754100000004)\r\nInternational Baptist Academy,Malabon,1651020.294,13466057.45,POINT (120.96765219999997 14.668456299999999)\r\nPhilippine Marine Incorporated,Manila,1645022.573,13467875.35,POINT (120.98398270000001 14.616327699999994)\r\nMaria Montessori Children\'s School Foundation,Pasay,1637219.242,13468884.05,POINT (120.99304400000001 14.548487299999998)\r\nSt. Francis Academy,Para\xc3\xb1aque,1627880.386,13471097.86,POINT (121.012931 14.467270000000001)\r\nA. C. Herrera High School,Manila,1647139.825,13467407.73,POINT (120.97978200000001 14.634731)\r\nVicente Orestes Romualdez School,Manila,1643589.252,13470923.37,POINT (121.01136350000002 14.603868300000004)\r\nOur Help of Christian School,Manila,1642590.368,13472032.72,POINT (121.02132899999997 14.595184899999998)\r\nMalabon Cultural Institute,Malabon,1649763.037,13464961.71,POINT (120.95780899999997 14.65753)\r\nCabrini School,Quezon City,1647072.163,13471705.35,POINT (121.01838819999999 14.634142899999997)\r\nBethel High School,Manila,1643866.813,13467727.38,POINT (120.9826535 14.6062811)\r\nSt. Joseph School,Manila,1642395.402,13470084.63,POINT (121.00382900000001 14.593489999999997)\r\nInfant Jesus Learning Academy Of Quezon City,Quezon City,1648358.2,13472098.6,POINT (121.02192079999999 14.6453205)\r\nManuel L. Quezon High School,Manila,1646531.206,13467293.07,POINT (120.97875200000001 14.629441)\r\nVictoria School Foundation,Quezon City,1646427.248,13476011.49,POINT (121.05707089999997 14.628537399999995)\r\nMetro Manila College High School Division,Kalookan,1657851.543,13474716.55,POINT (121.04543829999997 14.7278143)\r\nPateros Catholic School,Pateros,1636818.985,13477145.32,POINT (121.06725630000001 14.545007)\r\nG. Lopez Jaena Elementary School,Manila,1644844.741,13470093.3,POINT (121.0039069 14.614781899999999)\r\nValenzuela Institute,Valenzuela,1655488.246,13464756.99,POINT (120.95597000000001 14.707280999999996)\r\nPineslight School,Makati,1638633.34,13474835.05,POINT (121.0465028 14.560782700000003)\r\nEspiritu Santo High School Annex,Manila,1645434.935,13467904.19,POINT (120.98424180000002 14.619912099999997)\r\nSt. Francis Guidance School,Quezon City,1658269.916,13475541.75,POINT (121.05285119999999 14.731449100000003)\r\nAlbatross Foundation Academy,Malabon,1649451.721,13466325.42,POINT (120.9700595 14.654824399999999)\r\nBethel Lutheran School,Manila,1645708.501,13467316,POINT (120.97895799999998 14.62229)\r\nLope K. Santos School,Manila,1640903.498,13471047.76,POINT (121.012481 14.580520000000002)\r\nBalara Academy,Quezon City,1650676.732,13477937.56,POINT (121.07437310000002 14.6654706)\r\nSan Francisco Vocationaal School,Quezon City,1647917.533,13471400.51,POINT (121.0156498 14.641490499999996)\r\nUniversity of Santo Tomas Junior High School,Manila,1644368.519,13468308.14,POINT (120.9878705 14.610642299999999)\r\nLegarda High School,Manila,1644812.437,13469522.45,POINT (120.99877890000002 14.6145011)\r\nManila Central University,Manila,1643562.99,13468602.63,POINT (120.99051600000001 14.603640000000002)\r\nSt Joseph Technical School,Las Pi\xc3\xb1as,1629354.394,13467441.68,POINT (120.98008699999997 14.480091)\r\nPayatas Academy,Payatas Academy,1655106.149,13480466.51,POINT (121.09709099999998 14.703961)\r\nSchool of Saint Anthony Annex Building,Quezon City,1658446.796,13477013.13,POINT (121.06606879999998 14.732985800000002)\r\n"Bethel Christian School Of Q. C., Inc.",Quezon City,1653886.239,13476321.97,POINT (121.05986000000001 14.693360999999994)\r\nCaloocan Academy,Malabon,1649189.264,13466494.13,POINT (120.971575 14.652543399999997)\r\nHoly Infant Academy,Muntinlupa,1619632.807,13474046.33,POINT (121.0394176 14.3955185)\r\nChristian Baptist Academy,Taguig,1636872.865,13476753.73,POINT (121.06373859999997 14.545475499999998)\r\nThree Angels Educational Center,Manila,1643208.796,13470592.58,POINT (121.00839199999999 14.600560999999999)\r\nGCF International Christian School,Pasig,1641863.287,13476468.1,POINT (121.06117270000001 14.588864099999997)\r\nBlessed Trinity School of Las Pi\xc3\xb1as,Las Pi\xc3\xb1as,1622452.316,13470908.5,POINT (121.01123000000001 14.42005)\r\nOur Lady of Fatima Children Learning Center,Las Pi\xc3\xb1as,1625789.535,13470405.97,POINT (121.0067157 14.449082399999998)\r\nUniversity of the East - Ramon Magsaysay,Quezon City,1643952.021,13471990.02,POINT (121.02094540000002 14.607021800000005)\r\nSt. John Learning Center,Quezon City,1654286.939,13481359.26,POINT (121.10511070000001 14.696842799999997)\r\nPiaget Learning Center,Piaget Learning Center,1653196.902,13477747.26,POINT (121.07266360000001 14.687371)\r\nSaint Nicholas High School,Saint Nicholas High School,1650260.361,13480936.7,POINT (121.10131479999998 14.6618521)\r\nMontessori de Manila,Las Pi\xc3\xb1as,1625045.611,13470883.3,POINT (121.0110036 14.4426109)\r\nLearning Garden Montessori School,Learning Garden Montessori School,1626508.937,13471213.34,POINT (121.01396839999998 14.455340399999997)\r\nVeritas Parochial School,Veritas Parochial School,1625487.675,13472742.9,POINT (121.0277087 14.4464565)\r\nMSA Academic Advancement Inst.,Quezon City,1647616.295,13477921.55,POINT (121.0742293 14.638872300000001)\r\nMead International School,Mead International School,1625718.699,13472750.3,POINT (121.02777510000001 14.448466199999997)\r\nPaisley Garden Academe,Paisley Garden Academe,1653772.86,13475212.17,POINT (121.04989050000002 14.692375799999999)\r\nHoly Trinity School,Obando,1657611.028,13461918.46,POINT (120.9304711 14.7257247)\r\nGreat Learning Educational Center,Quezon City,1646125.614,13475981.33,POINT (121.0568 14.625915600000004)\r\nCleanlars Child Montessori Center,Cleanlars Child Montessori Center,1645822.673,13476912.52,POINT (121.06516499999996 14.6232824)\r\nBright Beginnings Center,Bright Beginnings Center,1650772.147,13465970.76,POINT (120.96687349999999 14.666299800000003)\r\nWestfield School,Westfield School,1624478.178,13467839.34,POINT (120.98365920000002 14.437674599999996)\r\nYoung Achievers International School,Las Pi\xc3\xb1as,1627472.861,13468535.27,POINT (120.98991089999998 14.463725199999999)\r\nSouth Merville School,Para\xc3\xb1aque,1631987.104,13472320.44,POINT (121.02391359999999 14.5029886)\r\nLittle Friends and Future Leaders Academy,Para\xc3\xb1aque,1629412.386,13472238.93,POINT (121.0231814 14.480595399999999)\r\nFather Simpliciano Academy,Para\xc3\xb1aque,1629026.187,13472647.09,POINT (121.026848 14.477236300000001)\r\nWorld of Wonder Pre-School,Para\xc3\xb1aque,1629474.781,13471417.39,POINT (121.0158014 14.481138099999997)\r\nJesu Mariae International School,Para\xc3\xb1aque,1629668.499,13472958.2,POINT (121.02964269999997 14.482822999999994)\r\nJesus Flock Academy School,Jesus Flock Academy School,1645861.351,13479162.96,POINT (121.08538099999998 14.6236186)\r\nA1 Driving,A1 Driving,1645590.211,13481132.39,POINT (121.1030727 14.621261800000005)\r\nYamaha School of Music (Pearl River),Manila,1643289.712,13467766.82,POINT (120.9830078 14.601264400000003)\r\nPaulo Scholastic Chastity De Montessori Academy,Paulo Scholastic Chastity De Montessori Academy,1629116.094,13472786.98,POINT (121.0281046 14.478018300000002)\r\nClarion School,Pasig,1640584.252,13476256.95,POINT (121.05927589999999 14.5777445)\r\nLincolnshire Intermediate School,Pasig,1640641.729,13476273.67,POINT (121.05942609999997 14.578244199999999)\r\nRomarinda International School,Pasig,1641075.31,13476801.16,POINT (121.06416459999998 14.582013699999996)\r\nENG Learning Center,ENG Learning Center,1626515.121,13471035.88,POINT (121.01237419999997 14.455394199999999)\r\nAU-PARR Alabang Montessori International,AU-PARR Alabang Montessori International,1621488.19,13471051.18,POINT (121.01251169999998 14.4116618)\r\nSTI Caloocan,STI Caloocan,1649071.269,13467754.56,POINT (120.9828976 14.651517900000002)\r\nGospel Light Christian Academy,Gospel Light Christian Academy,1647336.703,13475808.94,POINT (121.05525139999997 14.636442199999998)\r\nImmaculate Mother Learning Center,Immaculate Mother Learning Center,1652342.701,13470697.12,POINT (121.0093311 14.679948200000004)\r\nSt. Dominic Savio School,St. Dominic Savio School,1652158.764,13470474.31,POINT (121.00732960000002 14.6783498)\r\nHoly Angels Montessori School,Holy Angels Montessori School,1644860.571,13477633.94,POINT (121.07164559999998 14.614919499999997)\r\nAMA Computer School,Manila,1643380.198,13470211.93,POINT (121.00497259999999 14.602050999999998)\r\nGolden Treasure Baptist Academy (GTBA),Golden Treasure Baptist Academy (GTBA),1635951.158,13470563.11,POINT (121.0081273 14.5374609)\r\nPathways Child Care and Educational Center,Quezon City,1648042.587,13473111.23,POINT (121.0310174 14.642577400000002)\r\nMary of Peace Annex,Mary of Peace Annex,1622587.843,13471182.06,POINT (121.0136874 14.421229099999998)\r\nMary of Peace Main,Mary of Peace Main,1622182.966,13471215.5,POINT (121.0139878 14.4177066)\r\nEarly Achievers Learning Center,Early Achievers Learning Center,1650840.418,13473110.3,POINT (121.03100909999999 14.666893099999996)\r\nInformatics,Informatics,1638391.387,13471723.59,POINT (121.018552 14.558679)\r\nMaranatha Christian School,Maranatha Christian School,1638768.792,13474847.79,POINT (121.0466172 14.5619604)\r\nMariana Academy of Maritime Studies Inc.,Manila,1640996.737,13467493.7,POINT (120.98055430000001 14.581330599999998)\r\nPasig Christian Academy,Pasig Christian Academy,1639314.77,13478105.04,POINT (121.0758776 14.566707399999999)\r\nOnly by Grace Academy,Manila,1641023.664,13468272.44,POINT (120.98754979999997 14.581564699999998)\r\nMater Carmelli Pre-School,Mater Carmelli Pre-School,1657300.341,13473199.95,POINT (121.03181439999999 14.723025399999994)\r\nIna ng Buhay Elementay and High School,Ina ng Buhay Elementay and High School,1657498,13472416.74,POINT (121.0247787 14.724742700000006)\r\nCreative Explorers,Quezon City,1650183.497,13474571.85,POINT (121.0441384 14.661184099999998)\r\n,Unknown,1627995.811,13466675.27,POINT (120.97320220000002 14.468273999999997)\r\nMeralco Sibol School,Meralco Sibol School,1650374.001,13471340.9,POINT (121.0151143 14.662839699999997)\r\nAsia school of Arts and Science,Asia school of Arts and Science,1651016.462,13475843.26,POINT (121.05555969999999 14.668423000000002)\r\nMontessori West School,Quezon City,1648897.182,13472832.47,POINT (121.0285133 14.650004899999997)\r\nAsian School of Hospitality Arts,Quezon City,1649356.173,13472993.57,POINT (121.02996050000002 14.653994000000003)\r\nLas Pi\xc3\xb1as Montessori,Las Pi\xc3\xb1as,1627392.767,13467417.27,POINT (120.97986769999997 14.463028499999997)\r\nWoodRose Learning Center,WoodRose Learning Center,1653504.892,13464816.09,POINT (120.9565009 14.690047299999998)\r\nCastle Ville Academy,Quezon City,1649289.437,13472147.01,POINT (121.02235570000002 14.653413999999996)\r\nSaint William School of Pasig,Pasig,1637415.536,13478459.82,POINT (121.0790646 14.5501941)\r\nLRC Learning Center,Pateros,1637633.006,13477281.38,POINT (121.0684785 14.552085000000002)\r\nSt. John Bosco High School,Pateros,1636627.893,13477126.78,POINT (121.06708969999998 14.543345400000002)\r\nSanto Rosario Montessori,Santo Rosario Montessori,1651897.338,13468385.93,POINT (120.9885693 14.676077999999997)\r\nValenzuela Community School,Valenzuela Community School,1652317.741,13468629.56,POINT (120.9907579 14.679731300000002)\r\nBlessed Margaret Educational Center,Las Pi\xc3\xb1as,1625104.558,13471122.48,POINT (121.0131522 14.443123699999997)\r\nSKM,SKM,1651745.659,13468037.17,POINT (120.9854364 14.674759900000002)\r\nPrince N\' Princess School,Pasig,1640569.402,13479040.38,POINT (121.0842799 14.577615400000004)\r\nThe Learning House,The Learning House,1649178.587,13484125.81,POINT (121.1299631 14.652450600000003)\r\nSanto Ni\xc3\xb1o Montessori School,Quezon City,1656286.123,13475235.35,POINT (121.05009870000002 14.714213500000001)\r\n"Integrated Movement Academy, Inc.",Las Pi\xc3\xb1as,1624987.445,13468485.95,POINT (120.9894678 14.442104899999997)\r\nKen Care Learning Center,Las Pi\xc3\xb1as,1624938.935,13468546.36,POINT (120.99001050000001 14.441682900000005)\r\nSt. Teodora\'s Learning Center,Manila,1644328.565,13467035.97,POINT (120.9764424 14.610294999999997)\r\nSt. Mary\'s Angel School,St. Mary\'s Angel School,1654200.89,13469315.74,POINT (120.996922 14.6960951)\r\nInternational Graduate School of Leadership,International Graduate School of Leadership,1653202.794,13473431.88,POINT (121.0338979 14.687422200000004)\r\nSamantabhadra Institute,Manila,1645584.102,13467122.34,POINT (120.97721830000002 14.6212087)\r\nDo\xc3\xb1a Maria D. Fabros Memorial School,Manila,1640233.884,13468638.17,POINT (120.99083520000002 14.574698399999999)\r\nBlessed Angel School,Blessed Angel School,1659967.18,13475598.33,POINT (121.05335940000002 14.7461942)\r\nTorch to the Nations International School,Torch to the Nations International School,1653062.926,13476700.16,POINT (121.0632573 14.686206800000003)\r\nSt. Vincent\'s Seminary,St. Vincent\'s Seminary,1652221.273,13474074.26,POINT (121.0396685 14.678893000000002)\r\nAdvanced Science and Technology Institute,Advanced Science and Technology Institute,1648569.079,13477647.28,POINT (121.0717655 14.647153300000003)\r\nThe Growing Place,The Growing Place,1654762.52,13477150.59,POINT (121.06730360000002 14.7009752)\r\nFar East Advances School of Theology,Valenzuela,1653412.758,13465447.8,POINT (120.96217569999999 14.689246700000002)\r\nRegis Motessori,Regis Motessori,1631399.385,13474793.61,POINT (121.0461305 14.4978772)\r\nKinder Care Learning Center,Para\xc3\xb1aque,1625180.208,13471491.18,POINT (121.01646429999998 14.443781799999996)\r\nApple Tree Integrated School,Quezon City,1647064.04,13469362.13,POINT (120.9973387 14.6340723)\r\nSt. Mark\'s Learning Center,Quezon City,1645838.33,13473223.18,POINT (121.03202309999999 14.6234185)\r\nNorthern Rizal Yorklin School,Northern Rizal Yorklin School,1648393.948,13467445.53,POINT (120.98012160000002 14.645631200000002)\r\nSTI College Recto,Manila,1643391.748,13468186.41,POINT (120.986777 14.6021514)\r\nRoyal Philippines Educational Specialist,Manila,1643427.627,13468109.53,POINT (120.98608640000002 14.602463299999998)\r\nSaint Genevieve School of Pateros,Pateros,1636375.299,13477107.72,POINT (121.06691849999999 14.541148999999997)\r\nOur Lady of Fatima Parochial School,Manila,1642214.839,13471871.94,POINT (121.01988470000002 14.591920299999998)\r\nVillage School of Parkwood,Village School of Parkwood,1657517.256,13482471.24,POINT (121.1150998 14.724910000000001)\r\nPUP,Manila,1643240.857,13469875.47,POINT (121.0019501 14.600839699999996)\r\nMarymount Academy of Para\xc3\xb1aque,Marymount Academy of Para\xc3\xb1aque,1626002.479,13472527.47,POINT (121.02577339999999 14.4509348)\r\nOld Balara Christian Community School,Old Balara Christian Community School,1650572.055,13477565.78,POINT (121.07103330000001 14.664560899999998)\r\nMahatma Gandhi International School,Mahatma Gandhi International School,1632347.224,13472636.32,POINT (121.0267512 14.506120500000002)\r\n"Starland International School, Inc. (Cubao)","Starland International School, Inc. (Cubao)",1645100.699,13476096.8,POINT (121.05783730000002 14.617006800000002)\r\nGlendale School,Glendale School,1651065.068,13471871.42,POINT (121.01988000000001 14.668845400000002)\r\nThe Raya School,Quezon City,1646879.187,13473756.65,POINT (121.0368153 14.632465600000002)\r\nThe Elizabethan School,The Elizabethan School,1653193.955,13472839.61,POINT (121.02857740000002 14.687345400000002)\r\nSt Faustina School of Quezon City,St Faustina School of Quezon City,1653249.194,13472360.08,POINT (121.0242697 14.6878254)\r\nHoly Rosary Academy,Holy Rosary Academy,1627370.59,13468364.46,POINT (120.98837650000002 14.462835600000002)\r\n,Unknown,1647880.151,13477807.53,POINT (121.07320499999997 14.641165599999997)\r\nMaranatha Christian Academy,Caloocan,1650106.943,13466381.87,POINT (120.9705666 14.6605188)\r\nAsian Institute of Computer Studies,Asian Institute of Computer Studies,1647191.794,13480477.06,POINT (121.09718579999999 14.635182699999998)\r\nPromise Land Christian School,Promise Land Christian School,1656374.032,13482029.33,POINT (121.11113010000001 14.7149773)\r\nNuestra Se\xc3\xb

In [21]:
of = pd.read_csv("metro_manila_schools.csv")
of

,name,city,latitude,longitude,geometry
0,Gideon Academy,Gideon Academy,1636323.386,13469099.12,POINT (120.99497599999998 14.540697599999998)
1,NaN,Unknown,1648428.754,13482556.10,POINT (121.1158621 14.645933699999995)
2,The Children's House School,The Children's House School,1648888.725,13482812.06,POINT (121.11816149999997 14.6499314)
3,Victoria School,Victoria School,1649058.624,13482285.76,POINT (121.1134336 14.651408)
4,My Playland Learning Center,My Playland Learning Center,1649870.979,13482410.32,POINT (121.1145526 14.658468099999997)
...,...,...,...,...,...
1934,Claret,Claret,1650825.345,13475088.40,"POLYGON ((121.0485283 14.6666608, 121.0485961 ..."
1935,San Gabriel Elementary School,San Gabriel Elementary School,1655525.664,13475526.31,POLYGON ((121.05234449999998 14.70805219999999...
1936,"Liceo De Alabang, Inc.",Muntinlupa,1622697.365,13475124.90,"POLYGON ((121.0488338 14.421948100000003, 121...."
1937,Stone benches/covered walkway,Stone benches/covered walkway,1641985.399,13472437.29,"POLYGON ((121.02478329999998 14.5898024, 121.0..."
1938,University of the Philippines Diliman - Colleg...,University of the Philippines Diliman - Colleg...,1649641.888,13477404.51,"POLYGON ((121.06866880000001 14.6566312, 121.0..."

## Get an overview of the data and displaying it

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
oo = pd.read_csv(filename, skiprows=5)
oo

In [ ]:
oo.shape

In [ ]:
oo.shape?

In [ ]:
oo.head()

In [ ]:
oo.head?

In [ ]:
oo.head(3)

In [ ]:
oo.tail()

In [ ]:
oo.sample(5)

In [ ]:
oo.sample?

In [ ]:
oo.info()

In [ ]:
oo.describe()

In [ ]:
pd.get_option("display.max_rows")

In [ ]:
pd.set_option("display.max_rows", None)
oo

In [ ]:
pd.set_option("display.max_rows", 60)
oo

In [ ]:
pd.get_option("display.max_columns")

In [ ]:
pd.get_option("display.width")

In [ ]:
pd.set_option("display.width", 100)

## Select a Series (column)

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
oo = pd.read_csv(filename, skiprows=5)
oo.sample(3)

In [ ]:
type(oo)

In [ ]:
oo["Discipline"]

In [ ]:
oo['Discipline']

In [ ]:
#oo["discipline"]

In [ ]:
type(oo["Discipline"])

In [ ]:
oo.Discipline

In [ ]:
oo.columns

In [ ]:
oo["Athlete Name"]

In [ ]:
#oo.Athlete Name

In [ ]:
oo.sample(3)

In [ ]:
oo.Year.unique()

In [ ]:
oo.Year.unique?

In [ ]:
oo.Sport.unique()

In [ ]:
oo.sample(3)

In [ ]:
oo.Year.value_counts()

In [ ]:
oo.Year.value_counts?

In [ ]:
oo.Year.value_counts(normalize=True)

## Challenge

Answer the following questions. Indicate the Pandas command where relevant.

1.   What is the time range covered in this dataset?
2.   The Olympics take place every 4 years. Why are there missing years?
3.   What are the types of medals awarded?
4.   Across all of the Olympic Games, how many Gold, Silver and Bronze medals have there been?
5.   Why are there not an equal number of Gold, Silver and Bronze medals?
6.   There are more Gold medals than Silver, and more Silver than Bronze. Why might that be?
7.   What are the different NOCs (National Olympic Committees)
8.   What does the NOC 'ZZX' represent?

##Solution

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

1. What is the time range covered in this dataset?

In [ ]:
oo.Year.unique()

2. The Olympics take place every 4 years. Why are there missing years?
- World War 1: 1914-1918
- World War 2: 1939-1945

3. What are the types of medals awarded?

In [ ]:
oo.Medal.unique()

4. Across all of the Olympics, how many Gold, Silver and Bronze medals have there been?

In [ ]:
oo.Medal.value_counts()

5. Why are there not an equal number of Gold, Silver and Bronze medals?
- Tied results
- Team events
- Disqualifications

In [ ]:
oo.head(10)

6. There are more Gold medals than Silver, and more Silver than Bronze. Why might that be?

Men's 100km cycling
- https://en.wikipedia.org/wiki/Cycling_at_the_1896_Summer_Olympics_%E2%80%93_Men%27s_100_kilometres
- https://en.wikipedia.org/wiki/Aristidis_Konstantinidis

Men's 100m freestyle (1896)
- https://en.wikipedia.org/wiki/Swimming_at_the_1896_Summer_Olympics_%E2%80%93_Men%27s_100_metre_freestyle

7. What are the different NOCs (National Olympic Committees)

In [ ]:
oo.NOC.unique()

8. What does the NOC 'ZZX' represent?
- https://en.wikipedia.org/wiki/Mixed_teams_at_the_Olympics

## Python Lists and Dictionaries

In [ ]:
medals = ["Gold", "Silver", "Bronze"]
medals

In [ ]:
type(medals)

In [ ]:
position = {"First": "Gold",
            "Second": "Silver",
            "Third": "Bronze"
}
position

In [ ]:
type(position)

In [ ]:
position["First"]

## Rename a series (or column)

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
oo = pd.read_csv(filename, skiprows=5)
oo.sample(3)

In [ ]:
mapper = {"Athlete Name": "Athlete_Name",
          "Event Gender": "Event_Gender"}

In [ ]:
oo.rename?

In [ ]:
oo.rename(columns=mapper)

In [ ]:
oo.sample(3)

In [ ]:
oo = oo.rename(columns=mapper)
oo.sample(3)

In [ ]:
oo = pd.read_csv(filename, skiprows=5).rename(columns=mapper)
oo.sample(3)

In [ ]:
oo = pd.read_csv(filename, skiprows=5)
oo = oo.rename(columns={"Athlete Name": "Athlete_Name", "Event Gender": "Event_Gender"})
oo.sample(3)

In [ ]:
oo = pd.read_csv(filename, skiprows=5)
oo.columns

In [ ]:
column_names = ['Year', 'City', 'Sport', 'Discipline', 'Athlete_Name', 'NOC', 'Gender',
       'Event', 'Event_Gender', 'Medal', 'Position']
oo.columns = column_names
oo.sample(3)

In [ ]:
oo = pd.read_csv(filename, skiprows=5)
oo.sample(3)

In [ ]:
oo = pd.read_csv(filename, skiprows=5, names=column_names)
oo.head()

In [ ]:
oo = pd.read_csv(filename, skiprows=5, names=column_names, header=0)
oo.head()

## Remove a Series (column) or row

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
oo = pd.read_csv(filename, skiprows=5)
oo.sample(3)

In [ ]:
oo.drop('Position', axis=1)

In [ ]:
#oo.drop('Position', axis=0)

In [ ]:
oo.sample(3)

In [ ]:
oo = oo.drop('Position', axis=1)
oo.sample(3)

In [ ]:
oo = pd.read_csv(filename, skiprows=5).drop('Position', axis=1)
oo.sample(3)

In [ ]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.sample(3)

In [ ]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.sample(3)

In [ ]:
oo = pd.read_csv(filename, skiprows=5)
oo.drop('Position', axis=1, inplace=True)
oo.sample(3)

In [ ]:
#oo = (pd.read_csv(filename, skiprows=5)
#      .drop('Position', axis=1, inplace=True)
#)
#oo.sample(3)

In [ ]:
oo.drop?

In [ ]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.sample(3)

In [ ]:
oo.head(3)

In [ ]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop(2, axis=0)
)
oo.head(3)

In [ ]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop([0, 1, 3], axis=0)
)
oo.head(3)

In [ ]:
oo = oo.drop(['City', 'Sport'], axis=1)
oo.head(3)

In [ ]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.sample(3)

In [ ]:
pd.merge?

In [ ]:
pd.concat?

In [ ]:
oo.groupby?

## Filtering rows for a single condition

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.sample(3)

In [ ]:
type(True)

In [ ]:
type(False)

In [ ]:
oo.Year.dtype

In [ ]:
first_olympics = (oo.Year == 1896)
first_olympics

In [ ]:
oo[first_olympics]

In [ ]:
oo[oo.Year == 1896]

In [ ]:
oo[oo.Year < 1896]

In [ ]:
oo[(oo.Year <= 1896)]

## Filter rows for multiple conditions

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.tail(3)

In [ ]:
oo.dtypes

In [ ]:
oo[oo.City == 'Athens']

In [ ]:
#oo[oo.City == Athens]

In [ ]:
oo[(oo.Year == 1896) | (oo.Year == 2004)]

In [ ]:
oo[(oo.City == 'Athens') & (oo.Year == 2004)]

In [ ]:
oo[(oo.City == 'Athens') & ~(oo.Year == 1896)]

In [ ]:
first_men_100m = oo[(oo.Year == 1896) & (oo.Gender == 'Men') & (oo.Event == '100m')]
first_men_100m

In [ ]:
oo[(oo.Year == 1896) & (oo.Gender == 'Men') & (oo.Event == '100m')][["Year", "Athlete Name", "NOC", "Event", "Medal"]]

In [ ]:
first_men_100m[["Year", "Athlete Name", "NOC", "Event", "Medal"]]

## Using String methods

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.head(3)

In [ ]:
oo["Athlete Name"].str.lower()

In [ ]:
oo.Event.unique()

In [ ]:
oo.Event.str.capitalize()

In [ ]:
oo.Event = oo.Event.str.capitalize()
oo.Event.unique()

In [ ]:
dir(oo.Event.str)

In [ ]:
oo["Athlete Name"].str.contains("Latynina")

In [ ]:
# Larisa Latynina - most decorated Female athlete
oo[oo["Athlete Name"].str.contains("Latynina")]

In [ ]:
oo[oo["Athlete Name"].str.contains("LATYNINA")]

In [ ]:
dir(oo.Event.str)

In [ ]:
oo.City = oo.City.str.upper()
oo.sample(3)

In [ ]:
oo.City.unique()

## Sorting a DataFrame or Series

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.sample(3)

In [ ]:
oo["Athlete Name"].sort_values()

In [ ]:
type(oo["Athlete Name"].sort_values())

In [ ]:
oo.sort_values("Athlete Name")

In [ ]:
type(oo.sort_values("Athlete Name"))

In [ ]:
oo.head(3)

In [ ]:
oo.sort_values("Athlete Name", ascending=False)

In [ ]:
oo.sort_values("Athlete Name", ascending=False).head(25)

In [ ]:
oo.sort_values(by=['Year','Athlete Name'])

In [ ]:
oo.sort_values(by=["Year", "Athlete Name"], ascending=[False, True])

In [ ]:
oo.head(7)

In [ ]:
oo.sort_values(by=["Year", "Event", "Medal"], ascending=[True, True, False]).head(7)

In [ ]:
oo.dtypes

## Working with data types (dtype)

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.sample(3)

In [ ]:
oo.dtypes

In [ ]:
oo.Medal.unique()

In [ ]:
oo.Medal = oo.Medal.astype("category")
oo.dtypes

In [ ]:
oo.Gender.unique()

In [ ]:
oo['Event Gender'].unique()

In [ ]:
oo.Gender = oo.Gender.astype("category")
oo['Event Gender'] = oo['Event Gender'].astype("category")
oo.dtypes

In [ ]:
oo.Medal.astype("category")

In [ ]:
pd.Categorical?

In [ ]:
medal_order = ["Bronze", "Silver", "Gold"]
pd.Categorical(oo.Medal, categories=medal_order, ordered=True)

In [ ]:
oo.Medal = pd.Categorical(oo.Medal, categories=medal_order, ordered=True)
oo.dtypes

In [ ]:
oo.Medal

In [ ]:
oo.sort_values(by=["Year", "Event", "Medal"], ascending=[True, True, False]).head(7)

## Memory usage of different dtypes

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
df = pd.read_csv(filename, skiprows=5)
df.dtypes

In [ ]:
oo.dtypes

In [ ]:
oo.Medal.memory_usage?

In [ ]:
print(f"Medal series memory usage using dtype category: {oo.Medal.memory_usage(deep=True)}")
print(f"Medal series memory usage using dtype object: {df.Medal.memory_usage(deep=True)}")

In [ ]:
oo.Medal.memory_usage(deep=True) / df.Medal.memory_usage(deep=True)

In [ ]:
print(f"Gender series memory usage using dtype category: {oo.Gender.memory_usage(deep=True)}")
print(f"Gender series memory usage using dtype object: {df.Gender.memory_usage(deep=True)}")
print(f"Gender series memory usage using dtype category: {oo['Event Gender'].memory_usage(deep=True)}")
print(f"Gender series memory usage using dtype object: {df['Event Gender'].memory_usage(deep=True)}")

In [ ]:
oo.City.astype("string")

In [ ]:
oo.sample(2)

In [ ]:
oo.dtypes

In [ ]:
oo.City = oo.City.astype("string")
oo.Sport = oo.Sport.astype("string")
oo.Discipline = oo.Discipline.astype("string")
oo["Athlete Name"] = oo["Athlete Name"].astype("string")
oo.NOC = oo.NOC.astype("string")
oo.Event = oo.Event.astype("string")
oo.dtypes

In [ ]:
oo.City.dtype

In [ ]:
df.City.dtype

In [ ]:
print(f"City series memory usage using dtype string: {oo.City.memory_usage(deep=True)}")
print(f"City series memory usage using dtype object: {df.City.memory_usage(deep=True)}")

## Defining dtypes when you read in a file

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.sample(3)

In [ ]:
oo.dtypes

In [ ]:
dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": "category"}

dtype_mapper

In [ ]:
pd.api.types.CategoricalDtype?

In [ ]:
ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
ordered_medals

In [ ]:
dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}

dtype_mapper

In [ ]:
oo = pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
oo.sample(3)

In [ ]:
oo.dtypes

In [ ]:
oo["Event Gender"].unique()

In [ ]:
oo = pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
oo['Event Gender'] = oo['Event Gender'].astype("category")
oo.dtypes

## Python Functions

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def show_df(filename="olympics_1896_2004.csv"):
  """Read in csv file and display DataFrame"""
  df = pd.read_csv(filename, skiprows=5)
  return df

show_df()

In [ ]:
type(show_df())

In [ ]:
ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}

dtype_mapper

In [ ]:
oo = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
      .drop('Position', axis=1)
)
oo.sample(3)

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )

  return df

preprocess()

In [ ]:
preprocess()

In [ ]:
oo = preprocess()
oo.sample(3)

In [ ]:
oo.dtypes

In [ ]:
oo["Event Gender"].unique()

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df["Event Gender"] = df["Event Gender"].astype("category")
  return df

oo = preprocess()
oo.sample(3)

In [ ]:
oo.dtypes

## Working with Indexes

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df["Event Gender"] = df["Event Gender"].astype("category")
  return df

oo = preprocess()
oo.head(5)

In [ ]:
oo.index

In [ ]:
oo.columns

In [ ]:
oo.shape

In [ ]:
pd.read_csv(filename, skiprows=5, header=None).head()

In [ ]:
oo = preprocess()
oo.head(5)

In [ ]:
oo[oo['Athlete Name'].str.contains("LEWIS, Carl")]

In [ ]:
oo.loc[22719, "Event"]

In [ ]:
oo = oo.set_index("Athlete Name")
oo.head(5)

In [ ]:
oo.index

In [ ]:
oo.loc["LEWIS, Carl", "Event"]

In [ ]:
oo.head(3)

In [ ]:
oo.columns

In [ ]:
oo.shape

In [ ]:
oo.head(3)

In [ ]:
oo.loc["LEWIS, Carl", ["Year", "Event", "Medal"]]

In [ ]:
oo.loc["LEWIS, Carl", :]

In [ ]:
oo.loc["LEWIS, Carl"]

In [ ]:
oo = oo.sort_index()
oo.head(3)

In [ ]:
oo = oo.reset_index()
oo.head(3)

In [ ]:
oo.iloc[0, 0]

In [ ]:
oo.iloc[0, 5]

In [ ]:
oo.iloc[0, :]

In [ ]:
oo.iloc[0]

## Being Productive in pandas - My Best Practices

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df["Event Gender"] = df["Event Gender"].astype("category")
  return df

oo = preprocess()
oo.sample(3)

**Get immediate feedback**

In [ ]:
oo = preprocess()

In [ ]:
oo.sample(3)

In [ ]:
oo = preprocess()
oo.sample(3)

**Understand the basics of Python**

In [ ]:
dir(pd)

In [ ]:
[func.upper() for func in dir(pd)]

**Searching for method names**

In [ ]:
import re
import pandas as pd

search_string = "excel"

[func for func in dir(pd) if re.search(rf"{search_string}", func, re.IGNORECASE)]

In [ ]:
pd.read_excel?

In [ ]:
[func
 for func in dir(pd)
 if re.search(rf"{search_string}", func, re.IGNORECASE)]

**Documentation while staying in the IDE**

In [ ]:
pd.read_excel?

**head() vs. sample()**

In [ ]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.sample(3)

**Functions to preprocess data. Modify the data, not the original files**

In [ ]:
def preprocess(filename):
  """Transform the data. Change the dataframe and not the original csv files"""
  ...

preprocess(filename)

**Using python assert**

In [ ]:
oo[(oo.Year < 1896) & (oo.Year > 2004)].shape

In [ ]:
oo[(oo.Year < 1896) & (oo.Year > 2004)].shape[0] == 0

In [ ]:
assert(oo[(oo.Year < 1896) & (oo.Year > 2004)].shape[0] == 0)

In [ ]:
assert(oo[(oo.Year < 1896) & (oo.Year > 2004)].shape[0] == 0)
print("All tests passed")

In [ ]:
#assert(oo[(oo.Year < 1896) & (oo.Year > 2004)].shape[0] == (0, 10))
#print("All tests passed")

**Chaining and splitting over several rows. No inplace=True**

In [ ]:
oo = pd.read_csv(filename, skiprows=5)
oo = oo.drop('Position', axis=1)
oo.head(3)

In [ ]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.head(3)

In [ ]:
last3 = pd.read_csv(filename, skiprows=5).sort_values(['Year', 'Athlete Name']).tail(3)
last3

In [ ]:
last3 = (pd.read_csv(filename, skiprows=5)
        .sort_values(['Year', 'Athlete Name'])
        .tail(3)
)
last3

In [ ]:
last3 = (pd.read_csv(filename, skiprows=5)
#        .sort_values(['Year', 'Athlete Name'])
        .tail(3)
)
last3

**isin()**

In [ ]:
oo.Year.isin?

In [ ]:
years_of_interest = [1972, 1980, 1984, 1992, 2000, 2004]

In [ ]:
oo[oo.Year.isin(years_of_interest)]

In [ ]:
oo[~oo.Year.isin(years_of_interest)]

**Finding and dealing with missing values**

In [ ]:
oo.info()

## Creating Series and DataFrames

In [ ]:
import pandas as pd

In [ ]:
city = ["London", "Rio", "Tokyo"]
start_date = ["27th Jul, 2012", "5th Aug, 2016", "23rd July, 2021"]

In [ ]:
pd.Series(city)

In [ ]:
pd.DataFrame({"City": pd.Series(city),
              "Start Date": pd.Series(start_date)})

In [ ]:
pd.DataFrame({"City": city,
              "Start Date": start_date})

In [ ]:
pd.DataFrame(zip(city, start_date))

In [ ]:
pd.DataFrame(zip(city, start_date), columns=["City", "Start Date"])

## Working with dates

In [ ]:
import pandas as pd

In [ ]:
city = ["London", "Rio", "Tokyo"]
start_date = ["07-27-2012", "5th Aug, 2016", "23rd Jul, 2021"]
end_date = ["12th Aug, 2012", "21-08-2016", "8th Aug, 2021"]

In [ ]:
games = pd.DataFrame(zip(city, start_date, end_date), columns=["City", "Start Date", "End Date"])
games

In [ ]:
games.dtypes

In [ ]:
import re
import pandas as pd

search_string = "date"

[func for func in dir(pd) if re.search(rf"{search_string}", func, re.IGNORECASE)]

In [ ]:
pd.to_datetime?

In [ ]:
#pd.to_datetime(games["Start Date"])

In [ ]:
pd.to_datetime(games["Start Date"], format='mixed')

In [ ]:
games["Start Date"] = pd.to_datetime(games["Start Date"], format='mixed')
games["End Date"] = pd.to_datetime(games["End Date"], format='mixed')
games["City"] = games.City.astype("string")
games

In [ ]:
games.dtypes

In [ ]:
games["End Date"]

In [ ]:
games["Start Date"]

In [ ]:
games["End Date"] - games["Start Date"]

In [ ]:
games = games.assign(duration=games["End Date"] - games["Start Date"])
games

In [ ]:
games.dtypes

## Combining DataFrames

In [ ]:
import pandas as pd

In [ ]:
start = pd.DataFrame({"city": ["London", "Rio", "Tokyo"],
                      "start_date": ["27th Jul, 2012", "5th Aug, 2016", "23rd July, 2021"]})
start

In [ ]:
end = pd.DataFrame({"City": ["London", "Tokyo", "Paris"],
                    "end_date": ["12th Aug, 2012", "8th Aug, 2021", "11th Aug, 2024"]})
end

In [ ]:
pd.concat?

In [ ]:
pd.concat([start, end], axis=0)

In [ ]:
end = pd.DataFrame({"city": ["London", "Tokyo", "Paris"],
                    "end_date": ["12th Aug, 2012", "8th Aug, 2021", "11th Aug, 2024"]})
end

In [ ]:
pd.concat([start, end], axis=0)

In [ ]:
pd.concat([start, end], axis=1)

**Inner join**

In [ ]:
start

In [ ]:
end

In [ ]:
pd.merge?

In [ ]:
pd.merge(left=start, right=end, on="city", how="inner")

**Outer join**

In [ ]:
start

In [ ]:
end

In [ ]:
pd.merge(left=start, right=end, on="city", how="outer")

**Left join**

In [ ]:
start

In [ ]:
pd.merge(left=start, right=end, on="city", how="left")

**Right join**

In [ ]:
end

In [ ]:
pd.merge(left=start, right=end, on="city", how="right")

## Combining Datasets

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df["Event Gender"] = df["Event Gender"].astype("category")
  return df

preprocess()

In [ ]:
oo = preprocess()
oo.sample(3)

In [ ]:
!wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

In [ ]:
new_filename =  "olympics_2008.csv"
nw = pd.read_csv(new_filename)
nw.head(5)

In [ ]:
oo.sample(3)

In [ ]:
pd.concat([oo, nw], axis=0)

In [ ]:
nw.columns

In [ ]:
oo.columns

In [ ]:
nw.columns = ['City', 'Edition', 'Sport', 'Discipline', 'Athlete', 'Country_code',
       'Gender', 'Event', 'Event_gender', 'Medal', 'Result']
nw.columns

In [ ]:
new_columns = ['City', 'Edition', 'Sport', 'Discipline', 'Athlete', 'Country_code',
       'Gender', 'Event', 'Event_gender', 'Medal', 'Result']

In [ ]:
nw = pd.read_csv(new_filename, names=new_columns)
nw.columns

In [ ]:
nw.columns = [column.capitalize() for column in nw.columns]
nw.columns

In [ ]:
pd.concat([oo, nw], axis=0)

In [ ]:
oo.columns

In [ ]:
nw.columns

In [ ]:
nw.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']

In [ ]:
pd.concat([oo, nw], axis=0)

In [ ]:
nw.Result.unique()

In [ ]:
nw = nw.drop("Result", axis=1)
nw.sample(3)

In [ ]:
pd.concat([oo, nw], axis=0)

In [ ]:
pd.concat([oo, nw], axis=0).dtypes

In [ ]:
def preprocess_2008(filename="olympics_2008.csv"):
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  return df

nw = preprocess_2008()
nw.sample(3)

## Working with Missing Data

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
nw = preprocess_2008()
nw.sample(3)

In [ ]:
nw.info()

In [ ]:
import re

search_string = "na"

[func for func in dir(nw.City) if re.search(rf"{search_string}$", func, re.IGNORECASE)]

In [ ]:
nw.City.isna?

In [ ]:
nw.City.isna()

In [ ]:
nw.City.isna().sum()

In [ ]:
nw[nw.City.isna()]

In [ ]:
nw.City.unique()

In [ ]:
nw.shape

In [ ]:
import re

search_string = "na"

[func for func in dir(nw.City) if re.search(rf"{search_string}$", func, re.IGNORECASE)]

In [ ]:
nw.City.fillna?

In [ ]:
nw.City = nw.City.fillna(value="Beijing")
nw.City.unique()

In [ ]:
nw.Year

In [ ]:
nw.Year.unique()

In [ ]:
nw.Year = nw.Year.fillna(value=2008)
nw.info()

In [ ]:
def preprocess_2008(filename="olympics_2008.csv"):
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  return df

nw = preprocess_2008()
nw.sample(3)

In [ ]:
nw.dtypes

## Removing Missing Data

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess_2008(filename="olympics_2008.csv"):
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  return df

nw = preprocess_2008()
nw.sample(3)

In [ ]:
nw.info()

In [ ]:
nw[nw.Sport.isna()]

In [ ]:
nw.dropna(how="all", axis=0)

In [ ]:
nw.dropna(how="any", axis=0)

In [ ]:
nw[nw.Sport.isna()]

In [ ]:
nw.dropna?

In [ ]:
nw.columns

In [ ]:
nw.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")

In [ ]:
nw = nw.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
nw.info()

In [ ]:
def preprocess_2008(filename="olympics_2008.csv"):
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  return df

nw = preprocess_2008()
nw.sample(3)

##Working with Duplicates

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess_2008(filename="olympics_2008.csv"):
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  return df

nw = preprocess_2008()
nw.sample(3)

In [ ]:
nw.shape

In [ ]:
nw.duplicated?

In [ ]:
nw.duplicated()

In [ ]:
nw.duplicated().sum()

In [ ]:
nw.loc[nw.duplicated(), :]

In [ ]:
nw.shape

In [ ]:
nw = nw.drop_duplicates()
nw.shape

In [ ]:
nw.columns

In [ ]:
athlete_multiple_events = nw.duplicated(subset=['Athlete Name', 'NOC', 'Gender'])
athlete_multiple_events

In [ ]:
nw.duplicated?

In [ ]:
nw.loc[athlete_multiple_events, :]

In [ ]:
nw.loc[athlete_multiple_events, :].sort_values("Athlete Name")

In [ ]:
nw.loc[nw["Athlete Name"] == "ZOU, Kai"]

In [ ]:
def preprocess_2008(filename="olympics_2008.csv"):
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  return df

nw = preprocess_2008()
nw.sample(3)

## Validating data

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df["Event Gender"] = df["Event Gender"].astype("category")
  return df

oo = preprocess()

def preprocess_2008(filename="olympics_2008.csv"):
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  return df

nw = preprocess_2008()
nw.sample(3)

In [ ]:
nw["Event Gender"].unique()

In [ ]:
nw.Gender.unique()

In [ ]:
nw.loc[(nw["Event Gender"] == "M") & (nw.Gender != "Men")]

In [ ]:
nw.loc[(nw["Event Gender"] == "F") & (nw.Gender != "Women")]

In [ ]:
nw.loc[(nw.Gender == "Women") & ((nw["Event Gender"] != "W") & (nw["Event Gender"] != "X"))]

In [ ]:
nw.loc[(nw.Gender == "Men") & ((nw["Event Gender"] != "M") & (nw["Event Gender"] != "X"))]

In [ ]:
oo["Event Gender"].unique()

In [ ]:
oo.Gender.unique()

In [ ]:
oo.loc[(oo["Event Gender"] == "M") & (oo.Gender != "Men")]

In [ ]:
oo.loc[(oo["Event Gender"] == "F") & (oo.Gender != "Women")]

In [ ]:
oo.loc[(oo.Gender == "Women") & ((oo["Event Gender"] != "W") & (oo["Event Gender"] != "X"))]

In [ ]:
oo.loc[(oo.Gender == "Men") & ((oo["Event Gender"] != "M") & (oo["Event Gender"] != "X"))]

In [ ]:
oo.loc[(oo.Year == 2000) & (oo.Event == "marathon")]

In [ ]:
oo.loc[24676, "Gender"] = "Women"
oo.loc[(oo.Year == 2000) & (oo.Event == "marathon")]

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  return df

oo = preprocess()
oo.sample(3)

In [ ]:
oo.dtypes

In [ ]:
nw.Year.unique()

In [ ]:
nw.City.unique()

In [ ]:
nw["Event Gender"].unique()

In [ ]:
nw["Event Gender"].unique().tolist()

In [ ]:
oo["Event Gender"].unique().tolist()

In [ ]:
nw["Event Gender"].unique().tolist() == oo["Event Gender"].unique().tolist()

In [ ]:
sorted(nw["Event Gender"].unique().tolist())

In [ ]:
sorted(oo["Event Gender"].unique().tolist())

In [ ]:
assert(sorted(nw["Event Gender"].unique().tolist()) == sorted(oo["Event Gender"].unique().tolist()))
print("Passes all tests ...")

In [ ]:
#assert(sorted(nw["Event Gender"].unique().tolist()) == sorted(oo["Event Gender"].unique().tolist()))
#assert(sorted(nw.Gender.unique().tolist()) == sorted(oo.Gender.unique().tolist()))
#assert(sorted(nw.Medal.unique().tolist()) == sorted(oo.Medal.unique().tolist()))
#print("Passes all tests ...")

In [ ]:
sorted(oo.Medal.unique().tolist())

In [ ]:
sorted(nw.Medal.unique().tolist())

In [ ]:
nw.Medal.str.capitalize()

In [ ]:
nw.Medal = nw.Medal.str.capitalize()
nw.sample(3)

In [ ]:
assert(sorted(nw["Event Gender"].unique().tolist()) == sorted(oo["Event Gender"].unique().tolist()))
assert(sorted(nw.Gender.unique().tolist()) == sorted(oo.Gender.unique().tolist()))
assert(sorted(nw.Medal.unique().tolist()) == sorted(oo.Medal.unique().tolist()))
print("Passes all tests ...")

In [ ]:
sorted(nw.Sport.unique().tolist())

In [ ]:
sorted(oo.Sport.unique().tolist())

In [ ]:
nw.NOC.unique()

In [ ]:
nw.Sport = nw.Sport.str.lower()
nw.Discipline = nw.Discipline.str.lower()
nw.Event = nw.Event.str.lower()
nw.NOC = nw.NOC.str.upper()
nw.sample(3)

In [ ]:
def preprocess_2008(filename="olympics_2008.csv"):
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  return df

nw = preprocess_2008()
nw.sample(3)

## Further Data Validation

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df["Event Gender"] = df["Event Gender"].astype("category")
  return df

oo = preprocess()

def preprocess_2008(filename="olympics_2008.csv"):
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  return df

nw = preprocess_2008()
nw.sample(3)

In [ ]:
medals = ['Gold', 'Silver', 'Bronze', 'Bronze', 'Gold']
medals

In [ ]:
medals[0]

In [ ]:
medals[1]

In [ ]:
len(medals)

In [ ]:
nw["Athlete Name"]

In [ ]:
import re

search_string = "split"

[func for func in dir(nw["Athlete Name"].str) if re.search(rf"{search_string}", func, re.IGNORECASE)]

In [ ]:
nw["Athlete Name"].str.split?

In [ ]:
nw["Athlete Name"].str.split(", ")

In [ ]:
nw["Athlete Name"].str.split(", ").tolist()

In [ ]:
athlete_names = nw["Athlete Name"].str.split(", ").tolist()
athlete_names

In [ ]:
import re

search_string = "upper"

[func for func in dir(nw["Athlete Name"].str) if re.search(rf"{search_string}", func, re.IGNORECASE)]

In [ ]:
[athlete_name for athlete_name in athlete_names]

In [ ]:
[athlete_name[0] for athlete_name in athlete_names]

In [ ]:
[athlete_name[0].isupper() for athlete_name in athlete_names]

In [ ]:
len([item[0].isupper() for item in athlete_names])

In [ ]:
nw.info()

##Updating the dtypes

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  return df

def preprocess_2008(filename="olympics_2008.csv"):
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  return df

oo = preprocess()
nw = preprocess_2008()
nw.sample(3)

In [ ]:
nw.dtypes

In [ ]:
oo.dtypes

In [ ]:
def preprocess_2008(filename="olympics_2008.csv"):
  print(f"Preprocessing {filename} ...\n")
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  df.City = df.City.astype("string")
  df.Year = df.Year.astype(int)
  df.Sport = df.Sport.astype("string")
  df.Discipline = df.Discipline.astype("string")
  df["Athlete Name"] = df["Athlete Name"].astype("string")
  df.NOC = df.NOC.astype("string")
  df.Gender = df.Gender.astype("category")
  df.Event = df.Event.astype("string")
  df['Event Gender'] = df['Event Gender'].astype("category")
  medal_order = ["Bronze", "Silver", "Gold"]
  df.Medal = pd.Categorical(df.Medal, categories=medal_order, ordered=True)

  return df

nw = preprocess_2008()
nw.sample(3)

In [ ]:
nw.dtypes

## Combine the datasets

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  return df

def preprocess_2008(filename="olympics_2008.csv"):
  print(f"Preprocessing {filename} ...\n")
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  df.City = df.City.astype("string")
  df.Year = df.Year.astype(int)
  df.Sport = df.Sport.astype("string")
  df.Discipline = df.Discipline.astype("string")
  df["Athlete Name"] = df["Athlete Name"].astype("string")
  df.NOC = df.NOC.astype("string")
  df.Gender = df.Gender.astype("category")
  df.Event = df.Event.astype("string")
  df['Event Gender'] = df['Event Gender'].astype("category")
  medal_order = ["Bronze", "Silver", "Gold"]
  df.Medal = pd.Categorical(df.Medal, categories=medal_order, ordered=True)

  return df

In [ ]:
oo = preprocess()
oo.sample(3)

In [ ]:
oo.dtypes

In [ ]:
nw = preprocess_2008()
nw.sample(3)

In [ ]:
nw.dtypes

In [ ]:
pd.concat([oo, nw])

In [ ]:
pd.concat([oo, nw]).dtypes

In [ ]:
up = pd.concat([oo, nw])
up.sample(3)

In [ ]:
up.dtypes

##Plotting data

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt


if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  return df


def preprocess_2008(filename="olympics_2008.csv"):
  print(f"Preprocessing {filename} ...\n")
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  df.City = df.City.astype("string")
  df.Year = df.Year.astype(int)
  df.Sport = df.Sport.astype("string")
  df.Discipline = df.Discipline.astype("string")
  df["Athlete Name"] = df["Athlete Name"].astype("string")
  df.NOC = df.NOC.astype("string")
  df.Gender = df.Gender.astype("category")
  df.Event = df.Event.astype("string")
  df['Event Gender'] = df['Event Gender'].astype("category")
  medal_order = ["Bronze", "Silver", "Gold"]
  df.Medal = pd.Categorical(df.Medal, categories=medal_order, ordered=True)

  return df

oo = preprocess()
nw = preprocess_2008()
up = pd.concat([oo, nw])
up.sample(3)

In [ ]:
import matplotlib.pyplot as plt

**For the first Olympics, how many events were there for each of the different sports? Plot them using different graphs.**

In [ ]:
first_games = up[up.Year == 1896]
first_games

In [ ]:
first_games.Sport.value_counts()

In [ ]:
first_games.Sport.value_counts().plot?

In [ ]:
type(first_games.Sport.value_counts())

In [ ]:
dir(pd.Series)

In [ ]:
pd.Series.plot?

In [ ]:
first_games.Sport.value_counts().plot(kind='line')

In [ ]:
first_games.Sport.value_counts().plot(figsize=(10,3))

In [ ]:
(first_games
 .Sport
 .value_counts()
 .plot(figsize=(10,3))
)

In [ ]:
(first_games
 .Sport
 .value_counts()
 #.plot(figsize=(10,3))
)

In [ ]:
(first_games
 .Sport
 .value_counts()
 .plot(kind='bar')
)

In [ ]:
(first_games
 .Sport
 .value_counts()
 .plot
 .bar()
)

In [ ]:
(first_games
 .Sport
 .value_counts()
 .plot(kind='barh')
)

In [ ]:
(first_games
 .Sport
 .value_counts()
 .plot(kind='barh', color='red')
)

In [ ]:
(first_games
 .Sport
 .value_counts()
 .plot(kind='barh', color=['blue', 'red'])
)

##Working with colormaps and Seaborn

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  return df

def preprocess_2008(filename="olympics_2008.csv"):
  print(f"Preprocessing {filename} ...\n")
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  df.City = df.City.astype("string")
  df.Year = df.Year.astype(int)
  df.Sport = df.Sport.astype("string")
  df.Discipline = df.Discipline.astype("string")
  df["Athlete Name"] = df["Athlete Name"].astype("string")
  df.NOC = df.NOC.astype("string")
  df.Gender = df.Gender.astype("category")
  df.Event = df.Event.astype("string")
  df['Event Gender'] = df['Event Gender'].astype("category")
  medal_order = ["Bronze", "Silver", "Gold"]
  df.Medal = pd.Categorical(df.Medal, categories=medal_order, ordered=True)

  return df

oo = preprocess()
nw = preprocess_2008()
up = pd.concat([oo, nw])
up.sample(3)

In [ ]:
games_2008 = up[up.Year == 2008]
games_2008.sample(3)

In [ ]:
(games_2008
 .Medal
 .value_counts())

In [ ]:
import seaborn as sns

In [ ]:
plt.figure(figsize=(5,3))
plt.title("Medals from the 2008 games")
sns.countplot(data=games_2008,
              x='Medal',
              )

In [ ]:
plt.figure(figsize=(5,3))
plt.title("Medals from the 2008 games")
sns.countplot(data=games_2008,
              x='Medal',
              order=["Gold", "Silver", "Bronze"])

In [ ]:
plt.figure(figsize=(5,3))
plt.title("Medals from the 2008 games")
sns.countplot(data=games_2008,
              x='Medal',
              order=["Gold", "Silver", "Bronze"],
              hue='Gender')

In [ ]:
plt.figure(figsize=(5,3))
plt.title("Medals from the 2008 games")
sns.countplot(data=games_2008,
              x='Medal',
              order=["Gold", "Silver", "Bronze"],
              hue='Gender',
              palette='seismic')

In [ ]:
plt.figure(figsize=(5,3))
plt.title("Medals from the 2008 games")
sns.countplot(data=games_2008,
              x='Medal',
              order=["Gold", "Silver", "Bronze"],
              hue='Gender',
              palette='coolwarm')

In [ ]:
plt.figure(figsize=(5,3))
plt.title("Medals from the 2008 games")
sns.countplot(data=games_2008,
              x='Medal',
              order=["Gold", "Silver", "Bronze"],
              hue='Gender',
              palette='bwr')

In [ ]:
plt.figure(figsize=(5,3))
plt.title("Medals from the 2008 games")
sns.countplot(data=games_2008,
              x='Medal',
              order=["Gold", "Silver", "Bronze"],
              hue='Gender',
              palette='bwr_r')

##Working with groupby

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt


if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  return df

def preprocess_2008(filename="olympics_2008.csv"):
  print(f"Preprocessing {filename} ...\n")
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  df.City = df.City.astype("string")
  df.Year = df.Year.astype(int)
  df.Sport = df.Sport.astype("string")
  df.Discipline = df.Discipline.astype("string")
  df["Athlete Name"] = df["Athlete Name"].astype("string")
  df.NOC = df.NOC.astype("string")
  df.Gender = df.Gender.astype("category")
  df.Event = df.Event.astype("string")
  df['Event Gender'] = df['Event Gender'].astype("category")
  medal_order = ["Bronze", "Silver", "Gold"]
  df.Medal = pd.Categorical(df.Medal, categories=medal_order, ordered=True)

  return df

oo = preprocess()
nw = preprocess_2008()
up = pd.concat([oo, nw])
up.sample(3)

In [ ]:
sprints = up[(up.Year == 2008) & ((up.Event == '100m') | (up.Event == '200m'))]
sprints

In [ ]:
sp = sprints.groupby(['NOC', 'Gender', 'Event'])
sp

In [ ]:
up.groupby("Year")

In [ ]:
type(up.groupby('Year'))

In [ ]:
up.groupby("Year").count()

In [ ]:
for group_key, group_value in up.groupby('Year'):
    print(group_key)
    print(group_value)

In [ ]:
type(group_value)

In [ ]:
up.groupby(['Year']).count()

In [ ]:
up.groupby("Year").size()

In [ ]:
up.groupby(['Year','NOC']).count()

In [ ]:
up.groupby(['Year','NOC'])['Medal'].count()

In [ ]:
up.groupby(['Year','NOC']).size()

In [ ]:
up.groupby(['Year','NOC','Medal']).size()

In [ ]:
up.groupby(['NOC'])['Year'].min()

In [ ]:
up.groupby(['NOC'])['Year'].max()

In [ ]:
up.groupby(['NOC'])['Year'].min()

In [ ]:
up.groupby(['NOC'])['Year'].agg(['min', 'max', 'count'])

##Reshaping data: Stacking, Unstacking and MultiIndex

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt


if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
  df = df.drop('Position', axis=1)
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  return df

def preprocess_2008(filename="olympics_2008.csv"):
  print(f"Preprocessing {filename} ...\n")
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  df.City = df.City.astype("string")
  df.Year = df.Year.astype(int)
  df.Sport = df.Sport.astype("string")
  df.Discipline = df.Discipline.astype("string")
  df["Athlete Name"] = df["Athlete Name"].astype("string")
  df.NOC = df.NOC.astype("string")
  df.Gender = df.Gender.astype("category")
  df.Event = df.Event.astype("string")
  df['Event Gender'] = df['Event Gender'].astype("category")
  medal_order = ["Bronze", "Silver", "Gold"]
  df.Medal = pd.Categorical(df.Medal, categories=medal_order, ordered=True)

  return df

oo = preprocess()
nw = preprocess_2008()
up = pd.concat([oo, nw])
up.sample(3)

In [ ]:
sprints = up[(up.Year == 2008) & ( (up.Event == '100m') | (up.Event == '200m'))]
sprints

In [ ]:
sp = sprints.groupby(['NOC','Gender','Event']).size()
sp

In [ ]:
sp.unstack?

In [ ]:
sp.unstack('Gender', fill_value=0)

In [ ]:
(sp
 .unstack('Gender', fill_value=0)
 .unstack('Event', fill_value=0)
)

In [ ]:
sp.unstack?

In [ ]:
sp.unstack(['Gender', 'Event'], fill_value=0)

In [ ]:
sp = sprints.groupby(['NOC','Gender','Event']).size()
sp

In [ ]:
sp.unstack(level=1, fill_value=0)

In [ ]:
sprints_table = sp.unstack(level=1, fill_value=0).unstack(level=1, fill_value=0)
sprints_table

In [ ]:
sprints_NOC = sprints_table.stack("Gender")
sprints_NOC

In [ ]:
sprints_NOC.index

In [ ]:
sprints_NOC.loc[('JAM',   'Men'), :]

In [ ]:
sprints_NOC.loc[('JAM',   'Men'), '100m']

In [ ]:
sprints_NOC.iloc[0, :]

In [ ]:
sprints_NOC.iloc[0, 0]

In [ ]:
sprints_NOC.stack?

In [ ]:
sprints_NOC.unstack?

## Challenge

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
  df = df.drop('Position', axis=1)
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  return df

def preprocess_2008(filename="olympics_2008.csv"):
  print(f"Preprocessing {filename} ...\n")
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  df.City = df.City.astype("string")
  df.Year = df.Year.astype(int)
  df.Sport = df.Sport.astype("string")
  df.Discipline = df.Discipline.astype("string")
  df["Athlete Name"] = df["Athlete Name"].astype("string")
  df.NOC = df.NOC.astype("string")
  df.Gender = df.Gender.astype("category")
  df.Event = df.Event.astype("string")
  df['Event Gender'] = df['Event Gender'].astype("category")
  medal_order = ["Bronze", "Silver", "Gold"]
  df.Medal = pd.Categorical(df.Medal, categories=medal_order, ordered=True)

  return df

oo = preprocess()
nw = preprocess_2008()
up = pd.concat([oo, nw])
up.sample(3)

**Using a line graph, plot the number of gold medals won by the USA male and female Olympians throughout the history of the Olympics?
Distinguish between the male and female Olympians in the line graph using blue and pink**

**Using a bar chart, plot the 5 Olympians who have won the most gold medals from the dataset (1896 to 2008). When there is a tie, consider the number of silver medals, then bronze medals.**

##Solution

**Using a line graph, plot the number of gold medals won by the USA male and female Olympians throughout the history of the Olympics?
Distinguish between the male and female Olympians in the line graph using blue (male) and pink (female)**

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
  df = df.drop('Position', axis=1)
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  return df

def preprocess_2008(filename="olympics_2008.csv"):
  print(f"Preprocessing {filename} ...\n")
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  df.City = df.City.astype("string")
  df.Year = df.Year.astype(int)
  df.Sport = df.Sport.astype("string")
  df.Discipline = df.Discipline.astype("string")
  df["Athlete Name"] = df["Athlete Name"].astype("string")
  df.NOC = df.NOC.astype("string")
  df.Gender = df.Gender.astype("category")
  df.Event = df.Event.astype("string")
  df['Event Gender'] = df['Event Gender'].astype("category")
  medal_order = ["Bronze", "Silver", "Gold"]
  df.Medal = pd.Categorical(df.Medal, categories=medal_order, ordered=True)

  return df

oo = preprocess()
nw = preprocess_2008()
up = pd.concat([oo, nw])
up.sample(3)

In [ ]:
usa_gold = up[(up.NOC == 'USA') & (up.Medal == 'Gold')]
usa_gold

In [ ]:
usa_gold.groupby(['Year', 'Gender']).size()

In [ ]:
usa_gold.groupby(['Year', 'Gender']).size().index

In [ ]:
usa_gold.groupby(['Year', 'Gender']).size().plot(kind='line')

In [ ]:
usa_gold.groupby(['Year', 'Gender']).size()

In [ ]:
usa_gold.groupby(['Year', 'Gender']).size().unstack('Gender')

In [ ]:
usa_gold.groupby(['Year', 'Gender']).size().unstack('Gender').plot(kind='line')

In [ ]:
usa_gold.groupby(['Year', 'Gender']).size().unstack('Gender').plot?

In [ ]:
pd.Series.plot?

In [ ]:
usa_gold.groupby(['Year', 'Gender']).size().unstack('Gender').plot(kind='line', color=['blue', 'pink'])

In [ ]:
usa_gold.groupby(['Year', 'Gender']).size().unstack('Gender').plot(kind='line', color=['pink', 'blue'])

**Using a bar chart, plot the 5 Olympians who have won the most gold medals from the dataset (1896 to 2008). When there is a tie, consider the number of silver medals, then bronze medals.**

In [ ]:
up.groupby(['Athlete Name','Medal']).size()

In [ ]:
(up.groupby(['Athlete Name','Medal'])
.size()
.unstack('Medal', fill_value=0)
)

In [ ]:
(up.groupby(['Athlete Name','Medal'])
.size()
.unstack('Medal', fill_value=0)
.sort_values(['Gold', 'Silver', 'Bronze'], ascending=False)
)

In [ ]:
(up.groupby(['Athlete Name','Medal'])
.size()
.unstack('Medal', fill_value=0)
.sort_values(['Gold', 'Silver', 'Bronze'], ascending=False)[['Gold', 'Silver', 'Bronze']]
)

In [ ]:
(up.groupby(['Athlete Name','Medal'])
.size()
.unstack('Medal', fill_value=0)
.sort_values(['Gold', 'Silver', 'Bronze'], ascending=False)[['Gold', 'Silver', 'Bronze']]
.head(5)
)

In [ ]:
(up.groupby(['Athlete Name','Medal'])
.size()
.unstack('Medal', fill_value=0)
.sort_values(['Gold', 'Silver', 'Bronze'], ascending=False)[['Gold', 'Silver', 'Bronze']]
.head(5)
.plot(kind='bar')
)

##Creating your own colormaps

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
  df = df.drop('Position', axis=1)
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  return df

def preprocess_2008(filename="olympics_2008.csv"):
  print(f"Preprocessing {filename} ...\n")
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  df.City = df.City.astype("string")
  df.Year = df.Year.astype(int)
  df.Sport = df.Sport.astype("string")
  df.Discipline = df.Discipline.astype("string")
  df["Athlete Name"] = df["Athlete Name"].astype("string")
  df.NOC = df.NOC.astype("string")
  df.Gender = df.Gender.astype("category")
  df.Event = df.Event.astype("string")
  df['Event Gender'] = df['Event Gender'].astype("category")
  medal_order = ["Bronze", "Silver", "Gold"]
  df.Medal = pd.Categorical(df.Medal, categories=medal_order, ordered=True)

  return df

oo = preprocess()
nw = preprocess_2008()
up = pd.concat([oo, nw])
up.sample(3)

In [ ]:
(up.groupby(['Athlete Name','Medal'])
.size()
.unstack('Medal', fill_value=0)
.sort_values(['Gold', 'Silver', 'Bronze'], ascending=False)[['Gold', 'Silver', 'Bronze']]
.head(5)
.plot(kind='bar')
)

In [ ]:
from matplotlib.colors import ListedColormap

In [ ]:
ListedColormap?

In [ ]:
gold_silver_bronze = ['#dbb40c','#c5c9c7','#a87900']

In [ ]:
colormap = ListedColormap(gold_silver_bronze)
colormap

In [ ]:
(up.groupby(['Athlete Name','Medal'])
.size()
.unstack('Medal', fill_value=0)
.sort_values(['Gold', 'Silver', 'Bronze'], ascending=False)[['Gold', 'Silver', 'Bronze']]
.head(5)
.plot(kind='bar', colormap=colormap)
)

##Final Challenge

For each Olympic year present in the dataset, show the US Olympian (and their sport) who has won the highest number of medals in that particular year.

- In the case of a tie, Gold > Silver > Bronze
- Include only one Olympian for each Olympic year i.e. If there are 2 Olympians in one year who have won exactly the same number and type of medals, then show only the first one based on sorting the names alphabetically by surname.

- You should show the the following columns for each Olympic year:
  - Athlete Name
  - Sport
  - Total

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
pd.set_option("display.width", 100)

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
  df = df.drop('Position', axis=1)
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  return df

def preprocess_2008(filename="olympics_2008.csv"):
  print(f"Preprocessing {filename} ...\n")
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  df.City = df.City.astype("string")
  df.Year = df.Year.astype(int)
  df.Sport = df.Sport.astype("string")
  df.Discipline = df.Discipline.astype("string")
  df["Athlete Name"] = df["Athlete Name"].astype("string")
  df.NOC = df.NOC.astype("string")
  df.Gender = df.Gender.astype("category")
  df.Event = df.Event.astype("string")
  df['Event Gender'] = df['Event Gender'].astype("category")
  medal_order = ["Bronze", "Silver", "Gold"]
  df.Medal = pd.Categorical(df.Medal, categories=medal_order, ordered=True)

  return df

oo = preprocess()
nw = preprocess_2008()
up = pd.concat([oo, nw])
up.sample(3)

##Solution

For each Olympic year present in the dataset, show the US Olympian (and their sport) who has won the highest number of medals in that particular year.

- In the case of a tie, Gold > Silver > Bronze
- Include only one Olympian for each Olympic year i.e. If there are 2 Olympians in one year who have won exactly the same number and type of medals, then show only the first one based on sorting the names alphabetically by surname.

- You should show the the following columns for each Olympic year:
  - Athlete Name
  - Sport
  - Total

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
pd.set_option("display.width", 100)

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
  df = df.drop('Position', axis=1)
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  return df

def preprocess_2008(filename="olympics_2008.csv"):
  print(f"Preprocessing {filename} ...\n")
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  df.City = df.City.astype("string")
  df.Year = df.Year.astype(int)
  df.Sport = df.Sport.astype("string")
  df.Discipline = df.Discipline.astype("string")
  df["Athlete Name"] = df["Athlete Name"].astype("string")
  df.NOC = df.NOC.astype("string")
  df.Gender = df.Gender.astype("category")
  df.Event = df.Event.astype("string")
  df['Event Gender'] = df['Event Gender'].astype("category")
  medal_order = ["Bronze", "Silver", "Gold"]
  df.Medal = pd.Categorical(df.Medal, categories=medal_order, ordered=True)

  return df

oo = preprocess()
nw = preprocess_2008()
up = pd.concat([oo, nw])
up.sample(3)

In [ ]:
usa_olympian = up[up.NOC == 'USA']
usa_olympian

In [ ]:
usa_olympian.groupby(['Year', 'Athlete Name', 'Medal', 'Sport']).size()

In [ ]:
(usa_olympian.groupby(['Year', 'Athlete Name', 'Medal', 'Sport'])
.size()
.unstack('Medal', fill_value=0)
)

In [ ]:
table = (usa_olympian.groupby(['Year', 'Athlete Name', 'Sport', 'Medal'])
.size()
.unstack('Medal', fill_value=0)
)
table

In [ ]:
table = (usa_olympian.groupby(['Year', 'Athlete Name', 'Sport', 'Medal'])
.size()
.unstack('Medal', fill_value=0)
.assign(Total=table['Gold']+table['Silver']+table['Bronze'])
)
table

In [ ]:
table = (usa_olympian.groupby(['Year', 'Athlete Name', 'Sport', 'Medal'])
.size()
.unstack('Medal', fill_value=0)
.assign(Total=table['Gold']+table['Silver']+table['Bronze'])
.reset_index()
)
table

In [ ]:
for year, group in table.groupby('Year'):
  print(group)

In [ ]:
for year, group in table.groupby('Year'):
  print(group.sort_values('Total', ascending=False))

In [ ]:
for year, group in table.groupby('Year'):
  print(group.sort_values(['Total', 'Gold', 'Silver', 'Bronze', 'Athlete Name'], ascending=False))

In [ ]:
for year, group in table.groupby('Year'):
  print(group.sort_values(['Total', 'Gold', 'Silver', 'Bronze', 'Athlete Name'], ascending=False).head(1))

In [ ]:
winners = [
    group.sort_values(['Total', 'Gold', 'Silver', 'Bronze', 'Athlete Name'], ascending=False).head(1)
    for year, group in table.groupby('Year')
]
winners

In [ ]:
winners[0]

In [ ]:
type(winners[0])

In [ ]:
pd.concat(winners)

In [ ]:
pd.concat(winners)[["Year",	"Athlete Name",	"Sport", "Total"]]

In [ ]:
pd.concat(winners)[["Year",	"Athlete Name",	"Sport", "Total"]].reset_index()

In [ ]:
pd.concat(winners)[["Year",	"Athlete Name",	"Sport", "Total"]].reset_index?

In [ ]:
pd.DataFrame.reset_index?

In [ ]:
pd.concat(winners)[["Year",	"Athlete Name",	"Sport", "Total"]].reset_index(drop=True)

In [ ]:
#SDG